// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'merge.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ConflictDetail {
  final String path;
  final ConflictKind kind;

  /// Blob ids of each side, handed back with the resolution so a note that
  /// changed in between is noticed.
  final String? oursId;
  final String? theirsId;

  /// Whole versions, for reading one side at a time. `None` when that side
  /// deleted the note.
  final String? ours;
  final String? theirs;
  final MergedNote merged;

  const ConflictDetail({
    required this.path,
    required this.kind,
    this.oursId,
    this.theirsId,
    this.ours,
    this.theirs,
    required this.merged,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      kind.hashCode ^
      oursId.hashCode ^
      theirsId.hashCode ^
      ours.hashCode ^
      theirs.hashCode ^
      merged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictDetail &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          kind == other.kind &&
          oursId == other.oursId &&
          theirsId == other.theirsId &&
          ours == other.ours &&
          theirs == other.theirs &&
          merged == other.merged;
}

class ConflictFile {
  final String path;
  final ConflictKind kind;

  /// Roughly how many lines each side changed.
  final int oursChanged;
  final int theirsChanged;

  /// Places where both sides changed the same lines.
  final int conflicts;

  const ConflictFile({
    required this.path,
    required this.kind,
    required this.oursChanged,
    required this.theirsChanged,
    required this.conflicts,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      kind.hashCode ^
      oursChanged.hashCode ^
      theirsChanged.hashCode ^
      conflicts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictFile &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          kind == other.kind &&
          oursChanged == other.oursChanged &&
          theirsChanged == other.theirsChanged &&
          conflicts == other.conflicts;
}

enum ConflictKind {
  /// Both sides edited the note.
  bothModified,

  /// Both sides created a note at the same path.
  bothAdded,

  /// The phone deleted the note; the remote edited it.
  deletedByUs,

  /// The remote deleted the note; the phone edited it.
  deletedByThem,
}

class PendingConflict {
  /// Where this device's commits were pushed, for merging on the desktop.
  final String sideBranch;

  /// The newest remote commit the sync could not merge.
  final RemoteCommit remote;
  final List<ConflictFile> files;

  /// Notes the remote changed that merge cleanly but are held back with the
  /// rest until the merge is done.
  final List<String> heldBack;

  const PendingConflict({
    required this.sideBranch,
    required this.remote,
    required this.files,
    required this.heldBack,
  });

  @override
  int get hashCode =>
      sideBranch.hashCode ^
      remote.hashCode ^
      files.hashCode ^
      heldBack.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PendingConflict &&
          runtimeType == other.runtimeType &&
          sideBranch == other.sideBranch &&
          remote == other.remote &&
          files == other.files &&
          heldBack == other.heldBack;
}

class RemoteCommit {
  final String id;
  final String summary;
  final String author;
  final PlatformInt64 timeMs;

  const RemoteCommit({
    required this.id,
    required this.summary,
    required this.author,
    required this.timeMs,
  });

  @override
  int get hashCode =>
      id.hashCode ^ summary.hashCode ^ author.hashCode ^ timeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RemoteCommit &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          summary == other.summary &&
          author == other.author &&
          timeMs == other.timeMs;
}

/// How the user settled one note.
class Resolution {
  final String path;

  /// The ids from the [`ConflictDetail`] the user looked at.
  final String? oursId;
  final String? theirsId;

  /// The note's text, or `None` to delete it.
  final String? content;

  const Resolution({
    required this.path,
    this.oursId,
    this.theirsId,
    this.content,
  });

  @override
  int get hashCode =>
      path.hashCode ^ oursId.hashCode ^ theirsId.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Resolution &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          oursId == other.oursId &&
          theirsId == other.theirsId &&
          content == other.content;
}
