// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'error.freezed.dart';

/// Why a git operation failed. The app maps these to advice the user can act on
/// (re-enter the token, check the network, resolve on desktop).
enum GitErrorKind {
  auth,
  network,
  certificate,
  notARepo,
  noRemote,
  nonFastForward,
  conflict,
  other,
}

@freezed
sealed class PattoError with _$PattoError implements FrbException {
  const PattoError._();

  const factory PattoError.io(String field0) = PattoError_Io;
  const factory PattoError.notFound(String field0) = PattoError_NotFound;
  const factory PattoError.alreadyExists(String field0) =
      PattoError_AlreadyExists;
  const factory PattoError.invalidName(String field0) = PattoError_InvalidName;
  const factory PattoError.noTaskAtRow({
    required String path,
    required int row,
  }) = PattoError_NoTaskAtRow;
  const factory PattoError.indexNotBuilt(String field0) =
      PattoError_IndexNotBuilt;
  const factory PattoError.git({
    required GitErrorKind kind,
    required String message,
  }) = PattoError_Git;
}
