// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'git.dart';
import 'index.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'events.freezed.dart';

@freezed
sealed class CloneEvent with _$CloneEvent {
  const CloneEvent._();

  const factory CloneEvent.progress({required GitProgress progress}) =
      CloneEvent_Progress;
  const factory CloneEvent.done() = CloneEvent_Done;
  const factory CloneEvent.failed({required Failure failure}) =
      CloneEvent_Failed;
}

class Failure {
  final String message;

  /// Set when the failure came from git, so the app can advise the user.
  final GitErrorKind? gitKind;

  const Failure({required this.message, this.gitKind});

  @override
  int get hashCode => message.hashCode ^ gitKind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Failure &&
          runtimeType == other.runtimeType &&
          message == other.message &&
          gitKind == other.gitKind;
}

@freezed
sealed class IndexEvent with _$IndexEvent {
  const IndexEvent._();

  const factory IndexEvent.progress({required IndexProgress progress}) =
      IndexEvent_Progress;
  const factory IndexEvent.done({required IndexStats stats}) = IndexEvent_Done;
  const factory IndexEvent.failed({required Failure failure}) =
      IndexEvent_Failed;
}

@freezed
sealed class SyncEvent with _$SyncEvent {
  const SyncEvent._();

  const factory SyncEvent.progress({required GitProgress progress}) =
      SyncEvent_Progress;
  const factory SyncEvent.done({required SyncReport report}) = SyncEvent_Done;
  const factory SyncEvent.failed({required Failure failure}) = SyncEvent_Failed;
}
