// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'git.freezed.dart';

class GitCreds {
  final String username;
  final String token;

  const GitCreds({required this.username, required this.token});

  @override
  int get hashCode => username.hashCode ^ token.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitCreds &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          token == other.token;
}

enum GitPhase {
  connecting,
  counting,
  receiving,
  resolving,
  checkingOut,
  committing,
  merging,
  pushing,
  done,
}

class GitProgress {
  final GitPhase phase;
  final int current;
  final int total;
  final BigInt bytes;

  const GitProgress({
    required this.phase,
    required this.current,
    required this.total,
    required this.bytes,
  });

  @override
  int get hashCode =>
      phase.hashCode ^ current.hashCode ^ total.hashCode ^ bytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitProgress &&
          runtimeType == other.runtimeType &&
          phase == other.phase &&
          current == other.current &&
          total == other.total &&
          bytes == other.bytes;
}

class GitStatus {
  final String branch;
  final List<String> dirty;
  final int ahead;
  final int behind;
  final bool hasRemote;

  /// The last sync stopped at a conflict that has not been merged yet.
  final bool conflictPending;

  const GitStatus({
    required this.branch,
    required this.dirty,
    required this.ahead,
    required this.behind,
    required this.hasRemote,
    required this.conflictPending,
  });

  @override
  int get hashCode =>
      branch.hashCode ^
      dirty.hashCode ^
      ahead.hashCode ^
      behind.hashCode ^
      hasRemote.hashCode ^
      conflictPending.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GitStatus &&
          runtimeType == other.runtimeType &&
          branch == other.branch &&
          dirty == other.dirty &&
          ahead == other.ahead &&
          behind == other.behind &&
          hasRemote == other.hasRemote &&
          conflictPending == other.conflictPending;
}

@freezed
sealed class MergeOutcome with _$MergeOutcome {
  const MergeOutcome._();

  const factory MergeOutcome.upToDate() = MergeOutcome_UpToDate;
  const factory MergeOutcome.fastForward() = MergeOutcome_FastForward;

  /// A merge commit was made; no lines clashed.
  const factory MergeOutcome.merged() = MergeOutcome_Merged;

  /// Both sides changed the same lines, so nothing was merged. The phone's
  /// commits were pushed to `side_branch` instead, and the remote's changes
  /// are held back until the merge is done.
  const factory MergeOutcome.conflicted({
    required String sideBranch,
    required List<String> paths,
  }) = MergeOutcome_Conflicted;
}

class SyncReport {
  final bool committed;
  final String? commitId;
  final MergeOutcome merge;
  final bool pushed;

  /// A merge that was pending has now been completed, on the desktop or in
  /// the app, and the side branch removed.
  final bool conflictCleared;

  /// Note paths that changed on disk during the sync, so the app can refresh
  /// just those.
  final List<String> changedPaths;

  const SyncReport({
    required this.committed,
    this.commitId,
    required this.merge,
    required this.pushed,
    required this.conflictCleared,
    required this.changedPaths,
  });

  @override
  int get hashCode =>
      committed.hashCode ^
      commitId.hashCode ^
      merge.hashCode ^
      pushed.hashCode ^
      conflictCleared.hashCode ^
      changedPaths.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncReport &&
          runtimeType == other.runtimeType &&
          committed == other.committed &&
          commitId == other.commitId &&
          merge == other.merge &&
          pushed == other.pushed &&
          conflictCleared == other.conflictCleared &&
          changedPaths == other.changedPaths;
}
