// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A link pointing at the current note.
class BackLink {
  final String sourceName;
  final String sourceRelPath;
  final int row;
  final String context;
  final String? targetAnchor;

  const BackLink({
    required this.sourceName,
    required this.sourceRelPath,
    required this.row,
    required this.context,
    this.targetAnchor,
  });

  @override
  int get hashCode =>
      sourceName.hashCode ^
      sourceRelPath.hashCode ^
      row.hashCode ^
      context.hashCode ^
      targetAnchor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is BackLink &&
          runtimeType == other.runtimeType &&
          sourceName == other.sourceName &&
          sourceRelPath == other.sourceRelPath &&
          row == other.row &&
          context == other.context &&
          targetAnchor == other.targetAnchor;
}

/// Progress while scanning the notes directory.
class IndexProgress {
  final int scanned;
  final int total;
  final bool done;

  const IndexProgress({
    required this.scanned,
    required this.total,
    required this.done,
  });

  @override
  int get hashCode => scanned.hashCode ^ total.hashCode ^ done.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexProgress &&
          runtimeType == other.runtimeType &&
          scanned == other.scanned &&
          total == other.total &&
          done == other.done;
}

class IndexStats {
  final int notes;
  final int links;
  final int tasks;

  const IndexStats({
    required this.notes,
    required this.links,
    required this.tasks,
  });

  @override
  int get hashCode => notes.hashCode ^ links.hashCode ^ tasks.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is IndexStats &&
          runtimeType == other.runtimeType &&
          notes == other.notes &&
          links == other.links &&
          tasks == other.tasks;
}

/// How many notes link to each note, for the "most linked" sort.
class LinkCount {
  final String name;
  final String relPath;
  final int backlinks;
  final int outgoing;

  const LinkCount({
    required this.name,
    required this.relPath,
    required this.backlinks,
    required this.outgoing,
  });

  @override
  int get hashCode =>
      name.hashCode ^ relPath.hashCode ^ backlinks.hashCode ^ outgoing.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LinkCount &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          relPath == other.relPath &&
          backlinks == other.backlinks &&
          outgoing == other.outgoing;
}

/// Notes reachable in two hops: for each note this one links to, the other notes
/// that also link there.
class TwoHop {
  final String viaName;
  final List<String> names;

  const TwoHop({required this.viaName, required this.names});

  @override
  int get hashCode => viaName.hashCode ^ names.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TwoHop &&
          runtimeType == other.runtimeType &&
          viaName == other.viaName &&
          names == other.names;
}
