// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'merge.freezed.dart';

@freezed
sealed class MergeRegion with _$MergeRegion {
  const MergeRegion._();

  const factory MergeRegion.unchanged({required List<String> lines}) =
      MergeRegion_Unchanged;

  /// Only the phone changed these lines.
  const factory MergeRegion.ours({
    required List<String> base,
    required List<String> lines,
  }) = MergeRegion_Ours;

  /// Only the remote changed these lines.
  const factory MergeRegion.theirs({
    required List<String> base,
    required List<String> lines,
  }) = MergeRegion_Theirs;

  /// Both sides made the same change.
  const factory MergeRegion.same({
    required List<String> base,
    required List<String> lines,
  }) = MergeRegion_Same;
  const factory MergeRegion.conflict({
    required List<String> base,
    required List<String> ours,
    required List<String> theirs,
    Suggestion? suggestion,
  }) = MergeRegion_Conflict;
}

class MergedNote {
  final List<MergeRegion> regions;

  /// Whether the merged text should end with a newline.
  final bool trailingNewline;

  const MergedNote({required this.regions, required this.trailingNewline});

  @override
  int get hashCode => regions.hashCode ^ trailingNewline.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MergedNote &&
          runtimeType == other.runtimeType &&
          regions == other.regions &&
          trailingNewline == other.trailingNewline;
}

class Suggestion {
  final SuggestionKind kind;
  final List<String> lines;

  const Suggestion({required this.kind, required this.lines});

  @override
  int get hashCode => kind.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Suggestion &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          lines == other.lines;
}

/// How a suggested resolution was arrived at, so the app can label it.
enum SuggestionKind {
  /// Each side changed a different part of the same lines: one the text, the
  /// other the `{@...}` properties.
  combined,

  /// Both sides only added lines at the same place: keep both, ours first.
  both,
}
