// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'types.dart';

enum PendingGroup { overdue, today, thisWeek, later, noDue }

class TaskEditResult {
  final int row;
  final String newLine;

  const TaskEditResult({required this.row, required this.newLine});

  @override
  int get hashCode => row.hashCode ^ newLine.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskEditResult &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          newLine == other.newLine;
}

class TaskItem {
  final String relPath;
  final String noteName;
  final int row;
  final String text;
  final TaskInfo info;
  final PendingGroup group;

  /// Set only for completed tasks, `YYYY-MM-DD`.
  final String? completedOn;

  const TaskItem({
    required this.relPath,
    required this.noteName,
    required this.row,
    required this.text,
    required this.info,
    required this.group,
    this.completedOn,
  });

  @override
  int get hashCode =>
      relPath.hashCode ^
      noteName.hashCode ^
      row.hashCode ^
      text.hashCode ^
      info.hashCode ^
      group.hashCode ^
      completedOn.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskItem &&
          runtimeType == other.runtimeType &&
          relPath == other.relPath &&
          noteName == other.noteName &&
          row == other.row &&
          text == other.text &&
          info == other.info &&
          group == other.group &&
          completedOn == other.completedOn;
}
