// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'types.freezed.dart';

/// Where an anchor name lands in the flattened block list.
class AnchorRef {
  final String name;
  final int blockIndex;

  const AnchorRef({required this.name, required this.blockIndex});

  @override
  int get hashCode => name.hashCode ^ blockIndex.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AnchorRef &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          blockIndex == other.blockIndex;
}

class Block {
  /// 0-based source line the block starts on.
  final int row;

  /// Nesting level from tab indentation.
  final int depth;

  /// 0 outside a quote, 1 for `[@quote]`, 2 for a quote inside a quote.
  final int quoteDepth;
  final TaskInfo? task;
  final List<String> anchors;
  final BlockKind kind;

  const Block({
    required this.row,
    required this.depth,
    required this.quoteDepth,
    this.task,
    required this.anchors,
    required this.kind,
  });

  @override
  int get hashCode =>
      row.hashCode ^
      depth.hashCode ^
      quoteDepth.hashCode ^
      task.hashCode ^
      anchors.hashCode ^
      kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Block &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          depth == other.depth &&
          quoteDepth == other.quoteDepth &&
          task == other.task &&
          anchors == other.anchors &&
          kind == other.kind;
}

@freezed
sealed class BlockKind with _$BlockKind {
  const BlockKind._();

  const factory BlockKind.line({required List<NoteSpan> spans}) =
      BlockKind_Line;

  /// A line with no visible content; kept so vertical rhythm survives.
  const factory BlockKind.blank() = BlockKind_Blank;
  const factory BlockKind.code({
    required String lang,
    required List<String> lines,
  }) = BlockKind_Code;
  const factory BlockKind.math({required String tex}) = BlockKind_Math;
  const factory BlockKind.table({
    String? caption,
    required List<NoteTableRow> rows,
  }) = BlockKind_Table;

  /// A line whose entire content is images.
  const factory BlockKind.images({required List<ImageRef> images}) =
      BlockKind_Images;
  const factory BlockKind.rule() = BlockKind_Rule;
}

/// How a date-ish task field was understood, so the UI knows whether to show a
/// time and whether the value is a real date at all.
enum DateKind { date, dateTime, unparsed }

@freezed
sealed class EmbedKind with _$EmbedKind {
  const EmbedKind._();

  const factory EmbedKind.youtube({required String videoId}) =
      EmbedKind_Youtube;
  const factory EmbedKind.twitter() = EmbedKind_Twitter;
  const factory EmbedKind.speakerDeck() = EmbedKind_SpeakerDeck;
  const factory EmbedKind.slideShare() = EmbedKind_SlideShare;
  const factory EmbedKind.pdf() = EmbedKind_Pdf;
  const factory EmbedKind.other() = EmbedKind_Other;
}

class ImageRef {
  /// Remote URL, or a path relative to the notes root for local images.
  final String src;
  final String? alt;
  final bool isLocal;

  const ImageRef({required this.src, this.alt, required this.isLocal});

  @override
  int get hashCode => src.hashCode ^ alt.hashCode ^ isLocal.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ImageRef &&
          runtimeType == other.runtimeType &&
          src == other.src &&
          alt == other.alt &&
          isLocal == other.isLocal;
}

/// A note as listed on the notes screen.
class NoteMeta {
  /// Wiki-link name: path relative to the root, without the `.pn` extension.
  final String name;

  /// Path relative to the notes root, e.g. `dir/note.pn`.
  final String relPath;
  final PlatformInt64 modifiedMs;
  final BigInt sizeBytes;

  const NoteMeta({
    required this.name,
    required this.relPath,
    required this.modifiedMs,
    required this.sizeBytes,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      relPath.hashCode ^
      modifiedMs.hashCode ^
      sizeBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteMeta &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          relPath == other.relPath &&
          modifiedMs == other.modifiedMs &&
          sizeBytes == other.sizeBytes;
}

@freezed
sealed class NoteSpan with _$NoteSpan {
  const NoteSpan._();

  const factory NoteSpan.text({required String text}) = NoteSpan_Text;

  /// `[* bold]`, `[/ italic]`, `[_ underline]`, `[- deleted]`, nestable.
  const factory NoteSpan.decoration({
    required int fontsize,
    required bool italic,
    required bool underline,
    required bool deleted,
    required List<NoteSpan> children,
  }) = NoteSpan_Decoration;

  /// `[note]`, `[note#anchor]`, or `[#anchor]` (self link, `name` empty).
  const factory NoteSpan.wikiLink({required String name, String? anchor}) =
      NoteSpan_WikiLink;
  const factory NoteSpan.url({required String url, String? title}) =
      NoteSpan_Url;
  const factory NoteSpan.inlineCode({required String code}) =
      NoteSpan_InlineCode;
  const factory NoteSpan.inlineMath({required String tex}) =
      NoteSpan_InlineMath;
  const factory NoteSpan.image({required ImageRef image}) = NoteSpan_Image;
  const factory NoteSpan.embed({
    required String url,
    String? title,
    required EmbedKind kind,
  }) = NoteSpan_Embed;
}

class NoteTableCell {
  final List<NoteSpan> spans;

  const NoteTableCell({required this.spans});

  @override
  int get hashCode => spans.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteTableCell &&
          runtimeType == other.runtimeType &&
          spans == other.spans;
}

class NoteTableRow {
  final List<NoteTableCell> cells;

  const NoteTableRow({required this.cells});

  @override
  int get hashCode => cells.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NoteTableRow &&
          runtimeType == other.runtimeType &&
          cells == other.cells;
}

class ParseIssue {
  final int row;
  final String message;

  const ParseIssue({required this.row, required this.message});

  @override
  int get hashCode => row.hashCode ^ message.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParseIssue &&
          runtimeType == other.runtimeType &&
          row == other.row &&
          message == other.message;
}

class RenderedNote {
  final List<Block> blocks;
  final List<AnchorRef> anchors;
  final List<ParseIssue> errors;

  const RenderedNote({
    required this.blocks,
    required this.anchors,
    required this.errors,
  });

  @override
  int get hashCode => blocks.hashCode ^ anchors.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RenderedNote &&
          runtimeType == other.runtimeType &&
          blocks == other.blocks &&
          anchors == other.anchors &&
          errors == other.errors;
}

/// A task field rendered for display, e.g. `2026-12-31` / `2026-12-31T09:00`.
class TaskDate {
  final String text;
  final DateKind kind;

  const TaskDate({required this.text, required this.kind});

  @override
  int get hashCode => text.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskDate &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          kind == other.kind;
}

class TaskInfo {
  final TaskStatus status;
  final TaskDate? due;
  final TaskDate? scheduled;
  final TaskDate? completedAt;
  final TaskDate? startedAt;
  final int? timeSpentMinutes;

  /// `true` for `!2026-12-31`, `false` for `{@task ...}`.
  final bool isShorthand;

  const TaskInfo({
    required this.status,
    this.due,
    this.scheduled,
    this.completedAt,
    this.startedAt,
    this.timeSpentMinutes,
    required this.isShorthand,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      due.hashCode ^
      scheduled.hashCode ^
      completedAt.hashCode ^
      startedAt.hashCode ^
      timeSpentMinutes.hashCode ^
      isShorthand.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TaskInfo &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          due == other.due &&
          scheduled == other.scheduled &&
          completedAt == other.completedAt &&
          startedAt == other.startedAt &&
          timeSpentMinutes == other.timeSpentMinutes &&
          isShorthand == other.isShorthand;
}

enum TaskStatus { todo, doing, paused, done }
