// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/conflict.dart';
import 'api/error.dart';
import 'api/events.dart';
import 'api/git.dart';
import 'api/index.dart';
import 'api/merge.dart';
import 'api/tasks.dart';
import 'api/types.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Every note, most recently changed first.
///
/// The timestamps come from git where possible; see
/// [`index::apply_commit_times`] for why the filesystem cannot be trusted.
Future<List<NoteMeta>> listNotes({required String root}) =>
    RustLib.instance.api.crateFrbApiListNotes(root: root);

Future<String> readNote({required String root, required String relPath}) =>
    RustLib.instance.api.crateFrbApiReadNote(root: root, relPath: relPath);

Future<void> writeNote({
  required String root,
  required String relPath,
  required String content,
}) => RustLib.instance.api.crateFrbApiWriteNote(
  root: root,
  relPath: relPath,
  content: content,
);

Future<NoteMeta> createNote({
  required String root,
  required String name,
  required String initialContent,
}) => RustLib.instance.api.crateFrbApiCreateNote(
  root: root,
  name: name,
  initialContent: initialContent,
);

Future<void> deleteNote({required String root, required String relPath}) =>
    RustLib.instance.api.crateFrbApiDeleteNote(root: root, relPath: relPath);

Future<List<NoteMeta>> searchNotes({
  required String root,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateFrbApiSearchNotes(
  root: root,
  query: query,
  limit: limit,
);

/// Notes whose name or contents contain `query`, case-insensitively, with the
/// first `max_lines_per_note` matching lines of each.
Future<List<TextSearchHit>> searchText({
  required String root,
  required String query,
  required int maxNotes,
  required int maxLinesPerNote,
}) => RustLib.instance.api.crateFrbApiSearchText(
  root: root,
  query: query,
  maxNotes: maxNotes,
  maxLinesPerNote: maxLinesPerNote,
);

String? resolveWikiLink({required String root, required String name}) =>
    RustLib.instance.api.crateFrbApiResolveWikiLink(root: root, name: name);

String noteNameToRelPath({required String name}) =>
    RustLib.instance.api.crateFrbApiNoteNameToRelPath(name: name);

String relPathToNoteName({required String relPath}) =>
    RustLib.instance.api.crateFrbApiRelPathToNoteName(relPath: relPath);

Future<RenderedNote> renderNote({required String content}) =>
    RustLib.instance.api.crateFrbApiRenderNote(content: content);

/// Thumbnail and video stream from a Google Photos share page's HTML, which
/// Dart fetches with [`browser_user_agent`]. Asynchronous because a share
/// page runs to hundreds of kilobytes.
Future<GooglePhotosMedia?> parseGooglePhotosPage({required String html}) =>
    RustLib.instance.api.crateFrbApiParseGooglePhotosPage(html: html);

/// Title, thumbnail and description from a page's Open Graph tags, for embeds
/// whose site offers no oEmbed endpoint (Speaker Deck) or none at all.
Future<OpenGraphMeta> parseOpenGraph({required String html}) =>
    RustLib.instance.api.crateFrbApiParseOpenGraph(html: html);

/// The user agent Dart sends when fetching a page for its Open Graph tags:
/// Google serves share pages without them to unknown clients.
String browserUserAgent() => RustLib.instance.api.crateFrbApiBrowserUserAgent();

/// Scan the notes directory and build the link index.
///
/// The outcome arrives as the last event on the stream rather than as a return
/// value; see [`crate::api::events`] for why.
Stream<IndexEvent> indexBuild({required String root}) =>
    RustLib.instance.api.crateFrbApiIndexBuild(root: root);

Future<void> indexUpdateFile({required String root, required String relPath}) =>
    RustLib.instance.api.crateFrbApiIndexUpdateFile(
      root: root,
      relPath: relPath,
    );

/// Re-parse only the notes that changed on disk; used after a git sync.
Future<IndexStats> indexRefresh({required String root}) =>
    RustLib.instance.api.crateFrbApiIndexRefresh(root: root);

Future<List<BackLink>> backlinks({
  required String root,
  required String relPath,
}) => RustLib.instance.api.crateFrbApiBacklinks(root: root, relPath: relPath);

Future<List<TwoHop>> twoHopLinks({
  required String root,
  required String relPath,
}) => RustLib.instance.api.crateFrbApiTwoHopLinks(root: root, relPath: relPath);

Future<List<LinkCount>> linkCounts({required String root}) =>
    RustLib.instance.api.crateFrbApiLinkCounts(root: root);

bool noteExists({required String root, required String name}) =>
    RustLib.instance.api.crateFrbApiNoteExists(root: root, name: name);

Future<List<TaskItem>> pendingTasks({required String root}) =>
    RustLib.instance.api.crateFrbApiPendingTasks(root: root);

/// `timeframe` is one of `today`, `yesterday`, `this_week`, `last_week`,
/// `this_month`, `custom`; `from` / `to` are `YYYY-MM-DD` and only read for
/// `custom`.
Future<List<TaskItem>> completedTasks({
  required String root,
  required String timeframe,
  String? from,
  String? to,
}) => RustLib.instance.api.crateFrbApiCompletedTasks(
  root: root,
  timeframe: timeframe,
  from: from,
  to: to,
);

Future<TaskEditResult> setTaskStatus({
  required String root,
  required String relPath,
  required int row,
  required TaskStatus status,
}) => RustLib.instance.api.crateFrbApiSetTaskStatus(
  root: root,
  relPath: relPath,
  row: row,
  status: status,
);

/// Must be called before any other git function; see [`git::git_init_runtime`].
Future<void> gitInitRuntime({required String caBundlePath}) =>
    RustLib.instance.api.crateFrbApiGitInitRuntime(caBundlePath: caBundlePath);

Stream<CloneEvent> gitClone({
  required String url,
  required String root,
  String? branch,
  required GitCreds creds,
}) => RustLib.instance.api.crateFrbApiGitClone(
  url: url,
  root: root,
  branch: branch,
  creds: creds,
);

/// `attachments_dir` is the workspace's folder for inserted files, relative to
/// the root; it is synced along with the notes.
Future<GitStatus> gitStatus({
  required String root,
  required String attachmentsDir,
}) => RustLib.instance.api.crateFrbApiGitStatus(
  root: root,
  attachmentsDir: attachmentsDir,
);

Stream<SyncEvent> gitSync({
  required String root,
  required String attachmentsDir,
  required String authorName,
  required String authorEmail,
  required GitCreds creds,
}) => RustLib.instance.api.crateFrbApiGitSync(
  root: root,
  attachmentsDir: attachmentsDir,
  authorName: authorName,
  authorEmail: authorEmail,
  creds: creds,
);

/// The sync that stopped at a conflict, if one is waiting to be merged.
Future<PendingConflict?> pendingConflict({required String root}) =>
    RustLib.instance.api.crateFrbApiPendingConflict(root: root);

/// Base, phone and remote versions of one clashing note, split into regions.
Future<ConflictDetail> conflictDetail({
  required String root,
  required String relPath,
}) => RustLib.instance.api.crateFrbApiConflictDetail(
  root: root,
  relPath: relPath,
);

/// Merge with the user's choice for every clashing note and push. Reports like
/// [`git_sync`].
Stream<SyncEvent> gitResolve({
  required String root,
  required String attachmentsDir,
  required String authorName,
  required String authorEmail,
  required GitCreds creds,
  required List<Resolution> resolutions,
}) => RustLib.instance.api.crateFrbApiGitResolve(
  root: root,
  attachmentsDir: attachmentsDir,
  authorName: authorName,
  authorEmail: authorEmail,
  creds: creds,
  resolutions: resolutions,
);
