// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/error.dart';
import 'api/git.dart';
import 'api/index.dart';
import 'api/tasks.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_api.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateFrbApiInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => 541956740;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_patto_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<List<BackLink>> crateFrbApiBacklinks({
    required String root,
    required String relPath,
  });

  Future<List<TaskItem>> crateFrbApiCompletedTasks({
    required String root,
    required String timeframe,
    String? from,
    String? to,
  });

  Future<NoteMeta> crateFrbApiCreateNote({
    required String root,
    required String name,
    required String initialContent,
  });

  Future<void> crateFrbApiDeleteNote({
    required String root,
    required String relPath,
  });

  Stream<GitProgress> crateFrbApiGitClone({
    required String url,
    required String root,
    String? branch,
    required GitCreds creds,
  });

  Future<void> crateFrbApiGitInitRuntime({required String caBundlePath});

  Future<GitStatus> crateFrbApiGitStatus({required String root});

  Stream<GitProgress> crateFrbApiGitSync({
    required String root,
    required String authorName,
    required String authorEmail,
    required GitCreds creds,
  });

  Stream<IndexProgress> crateFrbApiIndexBuild({required String root});

  Future<IndexStats> crateFrbApiIndexRefresh({required String root});

  Future<void> crateFrbApiIndexUpdateFile({
    required String root,
    required String relPath,
  });

  Future<void> crateFrbApiInitApp();

  Future<List<LinkCount>> crateFrbApiLinkCounts({required String root});

  Future<List<NoteMeta>> crateFrbApiListNotes({required String root});

  bool crateFrbApiNoteExists({required String root, required String name});

  String crateFrbApiNoteNameToRelPath({required String name});

  Future<List<TaskItem>> crateFrbApiPendingTasks({required String root});

  Future<String> crateFrbApiReadNote({
    required String root,
    required String relPath,
  });

  String crateFrbApiRelPathToNoteName({required String relPath});

  Future<RenderedNote> crateFrbApiRenderNote({required String content});

  String? crateFrbApiResolveWikiLink({
    required String root,
    required String name,
  });

  Future<List<NoteMeta>> crateFrbApiSearchNotes({
    required String root,
    required String query,
    required int limit,
  });

  Future<TaskEditResult> crateFrbApiSetTaskStatus({
    required String root,
    required String relPath,
    required int row,
    required TaskStatus status,
  });

  Future<List<TwoHop>> crateFrbApiTwoHopLinks({
    required String root,
    required String relPath,
  });

  Future<void> crateFrbApiWriteNote({
    required String root,
    required String relPath,
    required String content,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<List<BackLink>> crateFrbApiBacklinks({
    required String root,
    required String relPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_back_link,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiBacklinksConstMeta,
        argValues: [root, relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiBacklinksConstMeta => const TaskConstMeta(
    debugName: "backlinks",
    argNames: ["root", "relPath"],
  );

  @override
  Future<List<TaskItem>> crateFrbApiCompletedTasks({
    required String root,
    required String timeframe,
    String? from,
    String? to,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(timeframe, serializer);
          sse_encode_opt_String(from, serializer);
          sse_encode_opt_String(to, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_item,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiCompletedTasksConstMeta,
        argValues: [root, timeframe, from, to],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCompletedTasksConstMeta => const TaskConstMeta(
    debugName: "completed_tasks",
    argNames: ["root", "timeframe", "from", "to"],
  );

  @override
  Future<NoteMeta> crateFrbApiCreateNote({
    required String root,
    required String name,
    required String initialContent,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(name, serializer);
          sse_encode_String(initialContent, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_note_meta,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiCreateNoteConstMeta,
        argValues: [root, name, initialContent],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiCreateNoteConstMeta => const TaskConstMeta(
    debugName: "create_note",
    argNames: ["root", "name", "initialContent"],
  );

  @override
  Future<void> crateFrbApiDeleteNote({
    required String root,
    required String relPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiDeleteNoteConstMeta,
        argValues: [root, relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiDeleteNoteConstMeta => const TaskConstMeta(
    debugName: "delete_note",
    argNames: ["root", "relPath"],
  );

  @override
  Stream<GitProgress> crateFrbApiGitClone({
    required String url,
    required String root,
    String? branch,
    required GitCreds creds,
  }) {
    final sink = RustStreamSink<GitProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(url, serializer);
            sse_encode_String(root, serializer);
            sse_encode_opt_String(branch, serializer);
            sse_encode_box_autoadd_git_creds(creds, serializer);
            sse_encode_StreamSink_git_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 5,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: sse_decode_patto_error,
          ),
          constMeta: kCrateFrbApiGitCloneConstMeta,
          argValues: [url, root, branch, creds, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateFrbApiGitCloneConstMeta => const TaskConstMeta(
    debugName: "git_clone",
    argNames: ["url", "root", "branch", "creds", "sink"],
  );

  @override
  Future<void> crateFrbApiGitInitRuntime({required String caBundlePath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(caBundlePath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiGitInitRuntimeConstMeta,
        argValues: [caBundlePath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGitInitRuntimeConstMeta => const TaskConstMeta(
    debugName: "git_init_runtime",
    argNames: ["caBundlePath"],
  );

  @override
  Future<GitStatus> crateFrbApiGitStatus({required String root}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_git_status,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiGitStatusConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiGitStatusConstMeta =>
      const TaskConstMeta(debugName: "git_status", argNames: ["root"]);

  @override
  Stream<GitProgress> crateFrbApiGitSync({
    required String root,
    required String authorName,
    required String authorEmail,
    required GitCreds creds,
  }) {
    final sink = RustStreamSink<GitProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(root, serializer);
            sse_encode_String(authorName, serializer);
            sse_encode_String(authorEmail, serializer);
            sse_encode_box_autoadd_git_creds(creds, serializer);
            sse_encode_StreamSink_git_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 8,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_sync_report,
            decodeErrorData: sse_decode_patto_error,
          ),
          constMeta: kCrateFrbApiGitSyncConstMeta,
          argValues: [root, authorName, authorEmail, creds, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateFrbApiGitSyncConstMeta => const TaskConstMeta(
    debugName: "git_sync",
    argNames: ["root", "authorName", "authorEmail", "creds", "sink"],
  );

  @override
  Stream<IndexProgress> crateFrbApiIndexBuild({required String root}) {
    final sink = RustStreamSink<IndexProgress>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_String(root, serializer);
            sse_encode_StreamSink_index_progress_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 9,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_index_stats,
            decodeErrorData: sse_decode_patto_error,
          ),
          constMeta: kCrateFrbApiIndexBuildConstMeta,
          argValues: [root, sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateFrbApiIndexBuildConstMeta =>
      const TaskConstMeta(debugName: "index_build", argNames: ["root", "sink"]);

  @override
  Future<IndexStats> crateFrbApiIndexRefresh({required String root}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_index_stats,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiIndexRefreshConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiIndexRefreshConstMeta =>
      const TaskConstMeta(debugName: "index_refresh", argNames: ["root"]);

  @override
  Future<void> crateFrbApiIndexUpdateFile({
    required String root,
    required String relPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiIndexUpdateFileConstMeta,
        argValues: [root, relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiIndexUpdateFileConstMeta => const TaskConstMeta(
    debugName: "index_update_file",
    argNames: ["root", "relPath"],
  );

  @override
  Future<void> crateFrbApiInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<List<LinkCount>> crateFrbApiLinkCounts({required String root}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_link_count,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiLinkCountsConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiLinkCountsConstMeta =>
      const TaskConstMeta(debugName: "link_counts", argNames: ["root"]);

  @override
  Future<List<NoteMeta>> crateFrbApiListNotes({required String root}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_meta,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiListNotesConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiListNotesConstMeta =>
      const TaskConstMeta(debugName: "list_notes", argNames: ["root"]);

  @override
  bool crateFrbApiNoteExists({required String root, required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiNoteExistsConstMeta,
        argValues: [root, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiNoteExistsConstMeta =>
      const TaskConstMeta(debugName: "note_exists", argNames: ["root", "name"]);

  @override
  String crateFrbApiNoteNameToRelPath({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiNoteNameToRelPathConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiNoteNameToRelPathConstMeta =>
      const TaskConstMeta(
        debugName: "note_name_to_rel_path",
        argNames: ["name"],
      );

  @override
  Future<List<TaskItem>> crateFrbApiPendingTasks({required String root}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_task_item,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiPendingTasksConstMeta,
        argValues: [root],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiPendingTasksConstMeta =>
      const TaskConstMeta(debugName: "pending_tasks", argNames: ["root"]);

  @override
  Future<String> crateFrbApiReadNote({
    required String root,
    required String relPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 18,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiReadNoteConstMeta,
        argValues: [root, relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiReadNoteConstMeta => const TaskConstMeta(
    debugName: "read_note",
    argNames: ["root", "relPath"],
  );

  @override
  String crateFrbApiRelPathToNoteName({required String relPath}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(relPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiRelPathToNoteNameConstMeta,
        argValues: [relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiRelPathToNoteNameConstMeta =>
      const TaskConstMeta(
        debugName: "rel_path_to_note_name",
        argNames: ["relPath"],
      );

  @override
  Future<RenderedNote> crateFrbApiRenderNote({required String content}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_rendered_note,
          decodeErrorData: null,
        ),
        constMeta: kCrateFrbApiRenderNoteConstMeta,
        argValues: [content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiRenderNoteConstMeta =>
      const TaskConstMeta(debugName: "render_note", argNames: ["content"]);

  @override
  String? crateFrbApiResolveWikiLink({
    required String root,
    required String name,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_String,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiResolveWikiLinkConstMeta,
        argValues: [root, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiResolveWikiLinkConstMeta => const TaskConstMeta(
    debugName: "resolve_wiki_link",
    argNames: ["root", "name"],
  );

  @override
  Future<List<NoteMeta>> crateFrbApiSearchNotes({
    required String root,
    required String query,
    required int limit,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(query, serializer);
          sse_encode_u_32(limit, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_note_meta,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiSearchNotesConstMeta,
        argValues: [root, query, limit],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSearchNotesConstMeta => const TaskConstMeta(
    debugName: "search_notes",
    argNames: ["root", "query", "limit"],
  );

  @override
  Future<TaskEditResult> crateFrbApiSetTaskStatus({
    required String root,
    required String relPath,
    required int row,
    required TaskStatus status,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          sse_encode_u_32(row, serializer);
          sse_encode_task_status(status, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 23,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_task_edit_result,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiSetTaskStatusConstMeta,
        argValues: [root, relPath, row, status],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiSetTaskStatusConstMeta => const TaskConstMeta(
    debugName: "set_task_status",
    argNames: ["root", "relPath", "row", "status"],
  );

  @override
  Future<List<TwoHop>> crateFrbApiTwoHopLinks({
    required String root,
    required String relPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 24,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_two_hop,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiTwoHopLinksConstMeta,
        argValues: [root, relPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiTwoHopLinksConstMeta => const TaskConstMeta(
    debugName: "two_hop_links",
    argNames: ["root", "relPath"],
  );

  @override
  Future<void> crateFrbApiWriteNote({
    required String root,
    required String relPath,
    required String content,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(root, serializer);
          sse_encode_String(relPath, serializer);
          sse_encode_String(content, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 25,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_patto_error,
        ),
        constMeta: kCrateFrbApiWriteNoteConstMeta,
        argValues: [root, relPath, content],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateFrbApiWriteNoteConstMeta => const TaskConstMeta(
    debugName: "write_note",
    argNames: ["root", "relPath", "content"],
  );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<GitProgress> dco_decode_StreamSink_git_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<IndexProgress> dco_decode_StreamSink_index_progress_Sse(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AnchorRef dco_decode_anchor_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AnchorRef(
      name: dco_decode_String(arr[0]),
      blockIndex: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  BackLink dco_decode_back_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return BackLink(
      sourceName: dco_decode_String(arr[0]),
      sourceRelPath: dco_decode_String(arr[1]),
      row: dco_decode_u_32(arr[2]),
      context: dco_decode_String(arr[3]),
      targetAnchor: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  Block dco_decode_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return Block(
      row: dco_decode_u_32(arr[0]),
      depth: dco_decode_u_32(arr[1]),
      quoteDepth: dco_decode_u_32(arr[2]),
      task: dco_decode_opt_box_autoadd_task_info(arr[3]),
      anchors: dco_decode_list_String(arr[4]),
      kind: dco_decode_block_kind(arr[5]),
    );
  }

  @protected
  BlockKind dco_decode_block_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return BlockKind_Line(spans: dco_decode_list_note_span(raw[1]));
      case 1:
        return BlockKind_Blank();
      case 2:
        return BlockKind_Code(
          lang: dco_decode_String(raw[1]),
          lines: dco_decode_list_String(raw[2]),
        );
      case 3:
        return BlockKind_Math(tex: dco_decode_String(raw[1]));
      case 4:
        return BlockKind_Table(
          caption: dco_decode_opt_String(raw[1]),
          rows: dco_decode_list_note_table_row(raw[2]),
        );
      case 5:
        return BlockKind_Images(images: dco_decode_list_image_ref(raw[1]));
      case 6:
        return BlockKind_Rule();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  EmbedKind dco_decode_box_autoadd_embed_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_embed_kind(raw);
  }

  @protected
  GitCreds dco_decode_box_autoadd_git_creds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_git_creds(raw);
  }

  @protected
  ImageRef dco_decode_box_autoadd_image_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_image_ref(raw);
  }

  @protected
  TaskDate dco_decode_box_autoadd_task_date(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_date(raw);
  }

  @protected
  TaskInfo dco_decode_box_autoadd_task_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_task_info(raw);
  }

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  DateKind dco_decode_date_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DateKind.values[raw as int];
  }

  @protected
  EmbedKind dco_decode_embed_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return EmbedKind_Youtube(videoId: dco_decode_String(raw[1]));
      case 1:
        return EmbedKind_Twitter();
      case 2:
        return EmbedKind_SpeakerDeck();
      case 3:
        return EmbedKind_SlideShare();
      case 4:
        return EmbedKind_Pdf();
      case 5:
        return EmbedKind_Other();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  GitCreds dco_decode_git_creds(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return GitCreds(
      username: dco_decode_String(arr[0]),
      token: dco_decode_String(arr[1]),
    );
  }

  @protected
  GitErrorKind dco_decode_git_error_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GitErrorKind.values[raw as int];
  }

  @protected
  GitPhase dco_decode_git_phase(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return GitPhase.values[raw as int];
  }

  @protected
  GitProgress dco_decode_git_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return GitProgress(
      phase: dco_decode_git_phase(arr[0]),
      current: dco_decode_u_32(arr[1]),
      total: dco_decode_u_32(arr[2]),
      bytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  GitStatus dco_decode_git_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return GitStatus(
      branch: dco_decode_String(arr[0]),
      dirty: dco_decode_list_String(arr[1]),
      ahead: dco_decode_u_32(arr[2]),
      behind: dco_decode_u_32(arr[3]),
      hasRemote: dco_decode_bool(arr[4]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  ImageRef dco_decode_image_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return ImageRef(
      src: dco_decode_String(arr[0]),
      alt: dco_decode_opt_String(arr[1]),
      isLocal: dco_decode_bool(arr[2]),
    );
  }

  @protected
  IndexProgress dco_decode_index_progress(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return IndexProgress(
      scanned: dco_decode_u_32(arr[0]),
      total: dco_decode_u_32(arr[1]),
      done: dco_decode_bool(arr[2]),
    );
  }

  @protected
  IndexStats dco_decode_index_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return IndexStats(
      notes: dco_decode_u_32(arr[0]),
      links: dco_decode_u_32(arr[1]),
      tasks: dco_decode_u_32(arr[2]),
    );
  }

  @protected
  LinkCount dco_decode_link_count(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return LinkCount(
      name: dco_decode_String(arr[0]),
      relPath: dco_decode_String(arr[1]),
      backlinks: dco_decode_u_32(arr[2]),
      outgoing: dco_decode_u_32(arr[3]),
    );
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<AnchorRef> dco_decode_list_anchor_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_anchor_ref).toList();
  }

  @protected
  List<BackLink> dco_decode_list_back_link(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_back_link).toList();
  }

  @protected
  List<Block> dco_decode_list_block(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_block).toList();
  }

  @protected
  List<ImageRef> dco_decode_list_image_ref(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_image_ref).toList();
  }

  @protected
  List<LinkCount> dco_decode_list_link_count(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_link_count).toList();
  }

  @protected
  List<NoteMeta> dco_decode_list_note_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_meta).toList();
  }

  @protected
  List<NoteSpan> dco_decode_list_note_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_span).toList();
  }

  @protected
  List<NoteTableCell> dco_decode_list_note_table_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_table_cell).toList();
  }

  @protected
  List<NoteTableRow> dco_decode_list_note_table_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_note_table_row).toList();
  }

  @protected
  List<ParseIssue> dco_decode_list_parse_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_parse_issue).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TaskItem> dco_decode_list_task_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_task_item).toList();
  }

  @protected
  List<TwoHop> dco_decode_list_two_hop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_two_hop).toList();
  }

  @protected
  MergeOutcome dco_decode_merge_outcome(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return MergeOutcome_UpToDate();
      case 1:
        return MergeOutcome_FastForward();
      case 2:
        return MergeOutcome_Merged(
          autoResolved: dco_decode_list_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NoteMeta dco_decode_note_meta(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return NoteMeta(
      name: dco_decode_String(arr[0]),
      relPath: dco_decode_String(arr[1]),
      modifiedMs: dco_decode_i_64(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
    );
  }

  @protected
  NoteSpan dco_decode_note_span(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return NoteSpan_Text(text: dco_decode_String(raw[1]));
      case 1:
        return NoteSpan_Decoration(
          fontsize: dco_decode_i_32(raw[1]),
          italic: dco_decode_bool(raw[2]),
          underline: dco_decode_bool(raw[3]),
          deleted: dco_decode_bool(raw[4]),
          children: dco_decode_list_note_span(raw[5]),
        );
      case 2:
        return NoteSpan_WikiLink(
          name: dco_decode_String(raw[1]),
          anchor: dco_decode_opt_String(raw[2]),
        );
      case 3:
        return NoteSpan_Url(
          url: dco_decode_String(raw[1]),
          title: dco_decode_opt_String(raw[2]),
        );
      case 4:
        return NoteSpan_InlineCode(code: dco_decode_String(raw[1]));
      case 5:
        return NoteSpan_InlineMath(tex: dco_decode_String(raw[1]));
      case 6:
        return NoteSpan_Image(image: dco_decode_box_autoadd_image_ref(raw[1]));
      case 7:
        return NoteSpan_Embed(
          url: dco_decode_String(raw[1]),
          title: dco_decode_opt_String(raw[2]),
          kind: dco_decode_box_autoadd_embed_kind(raw[3]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  NoteTableCell dco_decode_note_table_cell(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return NoteTableCell(spans: dco_decode_list_note_span(arr[0]));
  }

  @protected
  NoteTableRow dco_decode_note_table_row(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return NoteTableRow(cells: dco_decode_list_note_table_cell(arr[0]));
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  TaskDate? dco_decode_opt_box_autoadd_task_date(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_task_date(raw);
  }

  @protected
  TaskInfo? dco_decode_opt_box_autoadd_task_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_task_info(raw);
  }

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_32(raw);
  }

  @protected
  ParseIssue dco_decode_parse_issue(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ParseIssue(
      row: dco_decode_u_32(arr[0]),
      message: dco_decode_String(arr[1]),
    );
  }

  @protected
  PattoError dco_decode_patto_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return PattoError_Io(dco_decode_String(raw[1]));
      case 1:
        return PattoError_NotFound(dco_decode_String(raw[1]));
      case 2:
        return PattoError_AlreadyExists(dco_decode_String(raw[1]));
      case 3:
        return PattoError_InvalidName(dco_decode_String(raw[1]));
      case 4:
        return PattoError_NoTaskAtRow(
          path: dco_decode_String(raw[1]),
          row: dco_decode_u_32(raw[2]),
        );
      case 5:
        return PattoError_IndexNotBuilt(dco_decode_String(raw[1]));
      case 6:
        return PattoError_Git(
          kind: dco_decode_git_error_kind(raw[1]),
          message: dco_decode_String(raw[2]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  PendingGroup dco_decode_pending_group(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return PendingGroup.values[raw as int];
  }

  @protected
  RenderedNote dco_decode_rendered_note(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RenderedNote(
      blocks: dco_decode_list_block(arr[0]),
      anchors: dco_decode_list_anchor_ref(arr[1]),
      errors: dco_decode_list_parse_issue(arr[2]),
    );
  }

  @protected
  SyncReport dco_decode_sync_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return SyncReport(
      committed: dco_decode_bool(arr[0]),
      commitId: dco_decode_opt_String(arr[1]),
      merge: dco_decode_merge_outcome(arr[2]),
      pushed: dco_decode_bool(arr[3]),
      changedPaths: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  TaskDate dco_decode_task_date(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TaskDate(
      text: dco_decode_String(arr[0]),
      kind: dco_decode_date_kind(arr[1]),
    );
  }

  @protected
  TaskEditResult dco_decode_task_edit_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TaskEditResult(
      row: dco_decode_u_32(arr[0]),
      newLine: dco_decode_String(arr[1]),
    );
  }

  @protected
  TaskInfo dco_decode_task_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TaskInfo(
      status: dco_decode_task_status(arr[0]),
      due: dco_decode_opt_box_autoadd_task_date(arr[1]),
      scheduled: dco_decode_opt_box_autoadd_task_date(arr[2]),
      completedAt: dco_decode_opt_box_autoadd_task_date(arr[3]),
      startedAt: dco_decode_opt_box_autoadd_task_date(arr[4]),
      timeSpentMinutes: dco_decode_opt_box_autoadd_u_32(arr[5]),
      isShorthand: dco_decode_bool(arr[6]),
    );
  }

  @protected
  TaskItem dco_decode_task_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return TaskItem(
      relPath: dco_decode_String(arr[0]),
      noteName: dco_decode_String(arr[1]),
      row: dco_decode_u_32(arr[2]),
      text: dco_decode_String(arr[3]),
      info: dco_decode_task_info(arr[4]),
      group: dco_decode_pending_group(arr[5]),
      completedOn: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  TaskStatus dco_decode_task_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return TaskStatus.values[raw as int];
  }

  @protected
  TwoHop dco_decode_two_hop(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TwoHop(
      viaName: dco_decode_String(arr[0]),
      names: dco_decode_list_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<GitProgress> sse_decode_StreamSink_git_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<IndexProgress> sse_decode_StreamSink_index_progress_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AnchorRef sse_decode_anchor_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_blockIndex = sse_decode_u_32(deserializer);
    return AnchorRef(name: var_name, blockIndex: var_blockIndex);
  }

  @protected
  BackLink sse_decode_back_link(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sourceName = sse_decode_String(deserializer);
    var var_sourceRelPath = sse_decode_String(deserializer);
    var var_row = sse_decode_u_32(deserializer);
    var var_context = sse_decode_String(deserializer);
    var var_targetAnchor = sse_decode_opt_String(deserializer);
    return BackLink(
      sourceName: var_sourceName,
      sourceRelPath: var_sourceRelPath,
      row: var_row,
      context: var_context,
      targetAnchor: var_targetAnchor,
    );
  }

  @protected
  Block sse_decode_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_row = sse_decode_u_32(deserializer);
    var var_depth = sse_decode_u_32(deserializer);
    var var_quoteDepth = sse_decode_u_32(deserializer);
    var var_task = sse_decode_opt_box_autoadd_task_info(deserializer);
    var var_anchors = sse_decode_list_String(deserializer);
    var var_kind = sse_decode_block_kind(deserializer);
    return Block(
      row: var_row,
      depth: var_depth,
      quoteDepth: var_quoteDepth,
      task: var_task,
      anchors: var_anchors,
      kind: var_kind,
    );
  }

  @protected
  BlockKind sse_decode_block_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_spans = sse_decode_list_note_span(deserializer);
        return BlockKind_Line(spans: var_spans);
      case 1:
        return BlockKind_Blank();
      case 2:
        var var_lang = sse_decode_String(deserializer);
        var var_lines = sse_decode_list_String(deserializer);
        return BlockKind_Code(lang: var_lang, lines: var_lines);
      case 3:
        var var_tex = sse_decode_String(deserializer);
        return BlockKind_Math(tex: var_tex);
      case 4:
        var var_caption = sse_decode_opt_String(deserializer);
        var var_rows = sse_decode_list_note_table_row(deserializer);
        return BlockKind_Table(caption: var_caption, rows: var_rows);
      case 5:
        var var_images = sse_decode_list_image_ref(deserializer);
        return BlockKind_Images(images: var_images);
      case 6:
        return BlockKind_Rule();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  EmbedKind sse_decode_box_autoadd_embed_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_embed_kind(deserializer));
  }

  @protected
  GitCreds sse_decode_box_autoadd_git_creds(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_git_creds(deserializer));
  }

  @protected
  ImageRef sse_decode_box_autoadd_image_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_image_ref(deserializer));
  }

  @protected
  TaskDate sse_decode_box_autoadd_task_date(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_date(deserializer));
  }

  @protected
  TaskInfo sse_decode_box_autoadd_task_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_task_info(deserializer));
  }

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_32(deserializer));
  }

  @protected
  DateKind sse_decode_date_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DateKind.values[inner];
  }

  @protected
  EmbedKind sse_decode_embed_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_videoId = sse_decode_String(deserializer);
        return EmbedKind_Youtube(videoId: var_videoId);
      case 1:
        return EmbedKind_Twitter();
      case 2:
        return EmbedKind_SpeakerDeck();
      case 3:
        return EmbedKind_SlideShare();
      case 4:
        return EmbedKind_Pdf();
      case 5:
        return EmbedKind_Other();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  GitCreds sse_decode_git_creds(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_username = sse_decode_String(deserializer);
    var var_token = sse_decode_String(deserializer);
    return GitCreds(username: var_username, token: var_token);
  }

  @protected
  GitErrorKind sse_decode_git_error_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GitErrorKind.values[inner];
  }

  @protected
  GitPhase sse_decode_git_phase(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return GitPhase.values[inner];
  }

  @protected
  GitProgress sse_decode_git_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_phase = sse_decode_git_phase(deserializer);
    var var_current = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_bytes = sse_decode_u_64(deserializer);
    return GitProgress(
      phase: var_phase,
      current: var_current,
      total: var_total,
      bytes: var_bytes,
    );
  }

  @protected
  GitStatus sse_decode_git_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_branch = sse_decode_String(deserializer);
    var var_dirty = sse_decode_list_String(deserializer);
    var var_ahead = sse_decode_u_32(deserializer);
    var var_behind = sse_decode_u_32(deserializer);
    var var_hasRemote = sse_decode_bool(deserializer);
    return GitStatus(
      branch: var_branch,
      dirty: var_dirty,
      ahead: var_ahead,
      behind: var_behind,
      hasRemote: var_hasRemote,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  ImageRef sse_decode_image_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_src = sse_decode_String(deserializer);
    var var_alt = sse_decode_opt_String(deserializer);
    var var_isLocal = sse_decode_bool(deserializer);
    return ImageRef(src: var_src, alt: var_alt, isLocal: var_isLocal);
  }

  @protected
  IndexProgress sse_decode_index_progress(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_scanned = sse_decode_u_32(deserializer);
    var var_total = sse_decode_u_32(deserializer);
    var var_done = sse_decode_bool(deserializer);
    return IndexProgress(
      scanned: var_scanned,
      total: var_total,
      done: var_done,
    );
  }

  @protected
  IndexStats sse_decode_index_stats(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_notes = sse_decode_u_32(deserializer);
    var var_links = sse_decode_u_32(deserializer);
    var var_tasks = sse_decode_u_32(deserializer);
    return IndexStats(notes: var_notes, links: var_links, tasks: var_tasks);
  }

  @protected
  LinkCount sse_decode_link_count(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_relPath = sse_decode_String(deserializer);
    var var_backlinks = sse_decode_u_32(deserializer);
    var var_outgoing = sse_decode_u_32(deserializer);
    return LinkCount(
      name: var_name,
      relPath: var_relPath,
      backlinks: var_backlinks,
      outgoing: var_outgoing,
    );
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<AnchorRef> sse_decode_list_anchor_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <AnchorRef>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_anchor_ref(deserializer));
    }
    return ans_;
  }

  @protected
  List<BackLink> sse_decode_list_back_link(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <BackLink>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_back_link(deserializer));
    }
    return ans_;
  }

  @protected
  List<Block> sse_decode_list_block(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Block>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_block(deserializer));
    }
    return ans_;
  }

  @protected
  List<ImageRef> sse_decode_list_image_ref(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ImageRef>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_image_ref(deserializer));
    }
    return ans_;
  }

  @protected
  List<LinkCount> sse_decode_list_link_count(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <LinkCount>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_link_count(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteMeta> sse_decode_list_note_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteMeta>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_meta(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteSpan> sse_decode_list_note_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteSpan>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_span(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteTableCell> sse_decode_list_note_table_cell(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteTableCell>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_table_cell(deserializer));
    }
    return ans_;
  }

  @protected
  List<NoteTableRow> sse_decode_list_note_table_row(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <NoteTableRow>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_note_table_row(deserializer));
    }
    return ans_;
  }

  @protected
  List<ParseIssue> sse_decode_list_parse_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ParseIssue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_parse_issue(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TaskItem> sse_decode_list_task_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TaskItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_task_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<TwoHop> sse_decode_list_two_hop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TwoHop>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_two_hop(deserializer));
    }
    return ans_;
  }

  @protected
  MergeOutcome sse_decode_merge_outcome(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return MergeOutcome_UpToDate();
      case 1:
        return MergeOutcome_FastForward();
      case 2:
        var var_autoResolved = sse_decode_list_String(deserializer);
        return MergeOutcome_Merged(autoResolved: var_autoResolved);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NoteMeta sse_decode_note_meta(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_relPath = sse_decode_String(deserializer);
    var var_modifiedMs = sse_decode_i_64(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    return NoteMeta(
      name: var_name,
      relPath: var_relPath,
      modifiedMs: var_modifiedMs,
      sizeBytes: var_sizeBytes,
    );
  }

  @protected
  NoteSpan sse_decode_note_span(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_text = sse_decode_String(deserializer);
        return NoteSpan_Text(text: var_text);
      case 1:
        var var_fontsize = sse_decode_i_32(deserializer);
        var var_italic = sse_decode_bool(deserializer);
        var var_underline = sse_decode_bool(deserializer);
        var var_deleted = sse_decode_bool(deserializer);
        var var_children = sse_decode_list_note_span(deserializer);
        return NoteSpan_Decoration(
          fontsize: var_fontsize,
          italic: var_italic,
          underline: var_underline,
          deleted: var_deleted,
          children: var_children,
        );
      case 2:
        var var_name = sse_decode_String(deserializer);
        var var_anchor = sse_decode_opt_String(deserializer);
        return NoteSpan_WikiLink(name: var_name, anchor: var_anchor);
      case 3:
        var var_url = sse_decode_String(deserializer);
        var var_title = sse_decode_opt_String(deserializer);
        return NoteSpan_Url(url: var_url, title: var_title);
      case 4:
        var var_code = sse_decode_String(deserializer);
        return NoteSpan_InlineCode(code: var_code);
      case 5:
        var var_tex = sse_decode_String(deserializer);
        return NoteSpan_InlineMath(tex: var_tex);
      case 6:
        var var_image = sse_decode_box_autoadd_image_ref(deserializer);
        return NoteSpan_Image(image: var_image);
      case 7:
        var var_url = sse_decode_String(deserializer);
        var var_title = sse_decode_opt_String(deserializer);
        var var_kind = sse_decode_box_autoadd_embed_kind(deserializer);
        return NoteSpan_Embed(url: var_url, title: var_title, kind: var_kind);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  NoteTableCell sse_decode_note_table_cell(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_spans = sse_decode_list_note_span(deserializer);
    return NoteTableCell(spans: var_spans);
  }

  @protected
  NoteTableRow sse_decode_note_table_row(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cells = sse_decode_list_note_table_cell(deserializer);
    return NoteTableRow(cells: var_cells);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskDate? sse_decode_opt_box_autoadd_task_date(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_task_date(deserializer));
    } else {
      return null;
    }
  }

  @protected
  TaskInfo? sse_decode_opt_box_autoadd_task_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_task_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_32(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParseIssue sse_decode_parse_issue(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_row = sse_decode_u_32(deserializer);
    var var_message = sse_decode_String(deserializer);
    return ParseIssue(row: var_row, message: var_message);
  }

  @protected
  PattoError sse_decode_patto_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 = sse_decode_String(deserializer);
        return PattoError_Io(var_field0);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return PattoError_NotFound(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return PattoError_AlreadyExists(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return PattoError_InvalidName(var_field0);
      case 4:
        var var_path = sse_decode_String(deserializer);
        var var_row = sse_decode_u_32(deserializer);
        return PattoError_NoTaskAtRow(path: var_path, row: var_row);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return PattoError_IndexNotBuilt(var_field0);
      case 6:
        var var_kind = sse_decode_git_error_kind(deserializer);
        var var_message = sse_decode_String(deserializer);
        return PattoError_Git(kind: var_kind, message: var_message);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  PendingGroup sse_decode_pending_group(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return PendingGroup.values[inner];
  }

  @protected
  RenderedNote sse_decode_rendered_note(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_blocks = sse_decode_list_block(deserializer);
    var var_anchors = sse_decode_list_anchor_ref(deserializer);
    var var_errors = sse_decode_list_parse_issue(deserializer);
    return RenderedNote(
      blocks: var_blocks,
      anchors: var_anchors,
      errors: var_errors,
    );
  }

  @protected
  SyncReport sse_decode_sync_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_committed = sse_decode_bool(deserializer);
    var var_commitId = sse_decode_opt_String(deserializer);
    var var_merge = sse_decode_merge_outcome(deserializer);
    var var_pushed = sse_decode_bool(deserializer);
    var var_changedPaths = sse_decode_list_String(deserializer);
    return SyncReport(
      committed: var_committed,
      commitId: var_commitId,
      merge: var_merge,
      pushed: var_pushed,
      changedPaths: var_changedPaths,
    );
  }

  @protected
  TaskDate sse_decode_task_date(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_kind = sse_decode_date_kind(deserializer);
    return TaskDate(text: var_text, kind: var_kind);
  }

  @protected
  TaskEditResult sse_decode_task_edit_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_row = sse_decode_u_32(deserializer);
    var var_newLine = sse_decode_String(deserializer);
    return TaskEditResult(row: var_row, newLine: var_newLine);
  }

  @protected
  TaskInfo sse_decode_task_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_task_status(deserializer);
    var var_due = sse_decode_opt_box_autoadd_task_date(deserializer);
    var var_scheduled = sse_decode_opt_box_autoadd_task_date(deserializer);
    var var_completedAt = sse_decode_opt_box_autoadd_task_date(deserializer);
    var var_startedAt = sse_decode_opt_box_autoadd_task_date(deserializer);
    var var_timeSpentMinutes = sse_decode_opt_box_autoadd_u_32(deserializer);
    var var_isShorthand = sse_decode_bool(deserializer);
    return TaskInfo(
      status: var_status,
      due: var_due,
      scheduled: var_scheduled,
      completedAt: var_completedAt,
      startedAt: var_startedAt,
      timeSpentMinutes: var_timeSpentMinutes,
      isShorthand: var_isShorthand,
    );
  }

  @protected
  TaskItem sse_decode_task_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_relPath = sse_decode_String(deserializer);
    var var_noteName = sse_decode_String(deserializer);
    var var_row = sse_decode_u_32(deserializer);
    var var_text = sse_decode_String(deserializer);
    var var_info = sse_decode_task_info(deserializer);
    var var_group = sse_decode_pending_group(deserializer);
    var var_completedOn = sse_decode_opt_String(deserializer);
    return TaskItem(
      relPath: var_relPath,
      noteName: var_noteName,
      row: var_row,
      text: var_text,
      info: var_info,
      group: var_group,
      completedOn: var_completedOn,
    );
  }

  @protected
  TaskStatus sse_decode_task_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return TaskStatus.values[inner];
  }

  @protected
  TwoHop sse_decode_two_hop(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_viaName = sse_decode_String(deserializer);
    var var_names = sse_decode_list_String(deserializer);
    return TwoHop(viaName: var_viaName, names: var_names);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_git_progress_Sse(
    RustStreamSink<GitProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_git_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_StreamSink_index_progress_Sse(
    RustStreamSink<IndexProgress> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_index_progress,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_anchor_ref(AnchorRef self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_u_32(self.blockIndex, serializer);
  }

  @protected
  void sse_encode_back_link(BackLink self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sourceName, serializer);
    sse_encode_String(self.sourceRelPath, serializer);
    sse_encode_u_32(self.row, serializer);
    sse_encode_String(self.context, serializer);
    sse_encode_opt_String(self.targetAnchor, serializer);
  }

  @protected
  void sse_encode_block(Block self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.row, serializer);
    sse_encode_u_32(self.depth, serializer);
    sse_encode_u_32(self.quoteDepth, serializer);
    sse_encode_opt_box_autoadd_task_info(self.task, serializer);
    sse_encode_list_String(self.anchors, serializer);
    sse_encode_block_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_block_kind(BlockKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case BlockKind_Line(spans: final spans):
        sse_encode_i_32(0, serializer);
        sse_encode_list_note_span(spans, serializer);
      case BlockKind_Blank():
        sse_encode_i_32(1, serializer);
      case BlockKind_Code(lang: final lang, lines: final lines):
        sse_encode_i_32(2, serializer);
        sse_encode_String(lang, serializer);
        sse_encode_list_String(lines, serializer);
      case BlockKind_Math(tex: final tex):
        sse_encode_i_32(3, serializer);
        sse_encode_String(tex, serializer);
      case BlockKind_Table(caption: final caption, rows: final rows):
        sse_encode_i_32(4, serializer);
        sse_encode_opt_String(caption, serializer);
        sse_encode_list_note_table_row(rows, serializer);
      case BlockKind_Images(images: final images):
        sse_encode_i_32(5, serializer);
        sse_encode_list_image_ref(images, serializer);
      case BlockKind_Rule():
        sse_encode_i_32(6, serializer);
    }
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_embed_kind(
    EmbedKind self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_embed_kind(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_git_creds(
    GitCreds self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_git_creds(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_image_ref(
    ImageRef self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_image_ref(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_date(
    TaskDate self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_date(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_task_info(
    TaskInfo self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self, serializer);
  }

  @protected
  void sse_encode_date_kind(DateKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_embed_kind(EmbedKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case EmbedKind_Youtube(videoId: final videoId):
        sse_encode_i_32(0, serializer);
        sse_encode_String(videoId, serializer);
      case EmbedKind_Twitter():
        sse_encode_i_32(1, serializer);
      case EmbedKind_SpeakerDeck():
        sse_encode_i_32(2, serializer);
      case EmbedKind_SlideShare():
        sse_encode_i_32(3, serializer);
      case EmbedKind_Pdf():
        sse_encode_i_32(4, serializer);
      case EmbedKind_Other():
        sse_encode_i_32(5, serializer);
    }
  }

  @protected
  void sse_encode_git_creds(GitCreds self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.username, serializer);
    sse_encode_String(self.token, serializer);
  }

  @protected
  void sse_encode_git_error_kind(GitErrorKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_git_phase(GitPhase self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_git_progress(GitProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_git_phase(self.phase, serializer);
    sse_encode_u_32(self.current, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_u_64(self.bytes, serializer);
  }

  @protected
  void sse_encode_git_status(GitStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.branch, serializer);
    sse_encode_list_String(self.dirty, serializer);
    sse_encode_u_32(self.ahead, serializer);
    sse_encode_u_32(self.behind, serializer);
    sse_encode_bool(self.hasRemote, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_image_ref(ImageRef self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.src, serializer);
    sse_encode_opt_String(self.alt, serializer);
    sse_encode_bool(self.isLocal, serializer);
  }

  @protected
  void sse_encode_index_progress(IndexProgress self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.scanned, serializer);
    sse_encode_u_32(self.total, serializer);
    sse_encode_bool(self.done, serializer);
  }

  @protected
  void sse_encode_index_stats(IndexStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.notes, serializer);
    sse_encode_u_32(self.links, serializer);
    sse_encode_u_32(self.tasks, serializer);
  }

  @protected
  void sse_encode_link_count(LinkCount self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.relPath, serializer);
    sse_encode_u_32(self.backlinks, serializer);
    sse_encode_u_32(self.outgoing, serializer);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_anchor_ref(
    List<AnchorRef> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_anchor_ref(item, serializer);
    }
  }

  @protected
  void sse_encode_list_back_link(
    List<BackLink> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_back_link(item, serializer);
    }
  }

  @protected
  void sse_encode_list_block(List<Block> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_block(item, serializer);
    }
  }

  @protected
  void sse_encode_list_image_ref(
    List<ImageRef> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_image_ref(item, serializer);
    }
  }

  @protected
  void sse_encode_list_link_count(
    List<LinkCount> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_link_count(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_meta(
    List<NoteMeta> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_meta(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_span(
    List<NoteSpan> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_span(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_table_cell(
    List<NoteTableCell> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_table_cell(item, serializer);
    }
  }

  @protected
  void sse_encode_list_note_table_row(
    List<NoteTableRow> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_note_table_row(item, serializer);
    }
  }

  @protected
  void sse_encode_list_parse_issue(
    List<ParseIssue> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_parse_issue(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_task_item(
    List<TaskItem> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_task_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_two_hop(List<TwoHop> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_two_hop(item, serializer);
    }
  }

  @protected
  void sse_encode_merge_outcome(MergeOutcome self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case MergeOutcome_UpToDate():
        sse_encode_i_32(0, serializer);
      case MergeOutcome_FastForward():
        sse_encode_i_32(1, serializer);
      case MergeOutcome_Merged(autoResolved: final autoResolved):
        sse_encode_i_32(2, serializer);
        sse_encode_list_String(autoResolved, serializer);
    }
  }

  @protected
  void sse_encode_note_meta(NoteMeta self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.relPath, serializer);
    sse_encode_i_64(self.modifiedMs, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
  }

  @protected
  void sse_encode_note_span(NoteSpan self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case NoteSpan_Text(text: final text):
        sse_encode_i_32(0, serializer);
        sse_encode_String(text, serializer);
      case NoteSpan_Decoration(
        fontsize: final fontsize,
        italic: final italic,
        underline: final underline,
        deleted: final deleted,
        children: final children,
      ):
        sse_encode_i_32(1, serializer);
        sse_encode_i_32(fontsize, serializer);
        sse_encode_bool(italic, serializer);
        sse_encode_bool(underline, serializer);
        sse_encode_bool(deleted, serializer);
        sse_encode_list_note_span(children, serializer);
      case NoteSpan_WikiLink(name: final name, anchor: final anchor):
        sse_encode_i_32(2, serializer);
        sse_encode_String(name, serializer);
        sse_encode_opt_String(anchor, serializer);
      case NoteSpan_Url(url: final url, title: final title):
        sse_encode_i_32(3, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_String(title, serializer);
      case NoteSpan_InlineCode(code: final code):
        sse_encode_i_32(4, serializer);
        sse_encode_String(code, serializer);
      case NoteSpan_InlineMath(tex: final tex):
        sse_encode_i_32(5, serializer);
        sse_encode_String(tex, serializer);
      case NoteSpan_Image(image: final image):
        sse_encode_i_32(6, serializer);
        sse_encode_box_autoadd_image_ref(image, serializer);
      case NoteSpan_Embed(url: final url, title: final title, kind: final kind):
        sse_encode_i_32(7, serializer);
        sse_encode_String(url, serializer);
        sse_encode_opt_String(title, serializer);
        sse_encode_box_autoadd_embed_kind(kind, serializer);
    }
  }

  @protected
  void sse_encode_note_table_cell(
    NoteTableCell self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_note_span(self.spans, serializer);
  }

  @protected
  void sse_encode_note_table_row(NoteTableRow self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_note_table_cell(self.cells, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_task_date(
    TaskDate? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_task_date(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_task_info(
    TaskInfo? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_task_info(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_32(self, serializer);
    }
  }

  @protected
  void sse_encode_parse_issue(ParseIssue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.row, serializer);
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_patto_error(PattoError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case PattoError_Io(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_String(field0, serializer);
      case PattoError_NotFound(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case PattoError_AlreadyExists(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case PattoError_InvalidName(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
      case PattoError_NoTaskAtRow(path: final path, row: final row):
        sse_encode_i_32(4, serializer);
        sse_encode_String(path, serializer);
        sse_encode_u_32(row, serializer);
      case PattoError_IndexNotBuilt(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case PattoError_Git(kind: final kind, message: final message):
        sse_encode_i_32(6, serializer);
        sse_encode_git_error_kind(kind, serializer);
        sse_encode_String(message, serializer);
    }
  }

  @protected
  void sse_encode_pending_group(PendingGroup self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_rendered_note(RenderedNote self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_block(self.blocks, serializer);
    sse_encode_list_anchor_ref(self.anchors, serializer);
    sse_encode_list_parse_issue(self.errors, serializer);
  }

  @protected
  void sse_encode_sync_report(SyncReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.committed, serializer);
    sse_encode_opt_String(self.commitId, serializer);
    sse_encode_merge_outcome(self.merge, serializer);
    sse_encode_bool(self.pushed, serializer);
    sse_encode_list_String(self.changedPaths, serializer);
  }

  @protected
  void sse_encode_task_date(TaskDate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_date_kind(self.kind, serializer);
  }

  @protected
  void sse_encode_task_edit_result(
    TaskEditResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.row, serializer);
    sse_encode_String(self.newLine, serializer);
  }

  @protected
  void sse_encode_task_info(TaskInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_task_status(self.status, serializer);
    sse_encode_opt_box_autoadd_task_date(self.due, serializer);
    sse_encode_opt_box_autoadd_task_date(self.scheduled, serializer);
    sse_encode_opt_box_autoadd_task_date(self.completedAt, serializer);
    sse_encode_opt_box_autoadd_task_date(self.startedAt, serializer);
    sse_encode_opt_box_autoadd_u_32(self.timeSpentMinutes, serializer);
    sse_encode_bool(self.isShorthand, serializer);
  }

  @protected
  void sse_encode_task_item(TaskItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.relPath, serializer);
    sse_encode_String(self.noteName, serializer);
    sse_encode_u_32(self.row, serializer);
    sse_encode_String(self.text, serializer);
    sse_encode_task_info(self.info, serializer);
    sse_encode_pending_group(self.group, serializer);
    sse_encode_opt_String(self.completedOn, serializer);
  }

  @protected
  void sse_encode_task_status(TaskStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_two_hop(TwoHop self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.viaName, serializer);
    sse_encode_list_String(self.names, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
