// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/conflict.dart';
import 'api/error.dart';
import 'api/events.dart';
import 'api/git.dart';
import 'api/index.dart';
import 'api/merge.dart';
import 'api/tasks.dart';
import 'api/types.dart';

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;

import 'frb_api.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<CloneEvent> dco_decode_StreamSink_clone_event_Sse(dynamic raw);

  @protected
  RustStreamSink<IndexEvent> dco_decode_StreamSink_index_event_Sse(dynamic raw);

  @protected
  RustStreamSink<SyncEvent> dco_decode_StreamSink_sync_event_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AnchorRef dco_decode_anchor_ref(dynamic raw);

  @protected
  BackLink dco_decode_back_link(dynamic raw);

  @protected
  Block dco_decode_block(dynamic raw);

  @protected
  BlockKind dco_decode_block_kind(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  EmbedRef dco_decode_box_autoadd_embed_ref(dynamic raw);

  @protected
  Failure dco_decode_box_autoadd_failure(dynamic raw);

  @protected
  GitCreds dco_decode_box_autoadd_git_creds(dynamic raw);

  @protected
  GitErrorKind dco_decode_box_autoadd_git_error_kind(dynamic raw);

  @protected
  GitProgress dco_decode_box_autoadd_git_progress(dynamic raw);

  @protected
  GooglePhotosMedia dco_decode_box_autoadd_google_photos_media(dynamic raw);

  @protected
  ImageRef dco_decode_box_autoadd_image_ref(dynamic raw);

  @protected
  IndexProgress dco_decode_box_autoadd_index_progress(dynamic raw);

  @protected
  IndexStats dco_decode_box_autoadd_index_stats(dynamic raw);

  @protected
  PendingConflict dco_decode_box_autoadd_pending_conflict(dynamic raw);

  @protected
  Suggestion dco_decode_box_autoadd_suggestion(dynamic raw);

  @protected
  SyncReport dco_decode_box_autoadd_sync_report(dynamic raw);

  @protected
  TaskDate dco_decode_box_autoadd_task_date(dynamic raw);

  @protected
  TaskInfo dco_decode_box_autoadd_task_info(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_32(dynamic raw);

  @protected
  CloneEvent dco_decode_clone_event(dynamic raw);

  @protected
  ConflictDetail dco_decode_conflict_detail(dynamic raw);

  @protected
  ConflictFile dco_decode_conflict_file(dynamic raw);

  @protected
  ConflictKind dco_decode_conflict_kind(dynamic raw);

  @protected
  DateKind dco_decode_date_kind(dynamic raw);

  @protected
  EmbedKind dco_decode_embed_kind(dynamic raw);

  @protected
  EmbedRef dco_decode_embed_ref(dynamic raw);

  @protected
  Failure dco_decode_failure(dynamic raw);

  @protected
  GitCreds dco_decode_git_creds(dynamic raw);

  @protected
  GitErrorKind dco_decode_git_error_kind(dynamic raw);

  @protected
  GitPhase dco_decode_git_phase(dynamic raw);

  @protected
  GitProgress dco_decode_git_progress(dynamic raw);

  @protected
  GitStatus dco_decode_git_status(dynamic raw);

  @protected
  GooglePhotosMedia dco_decode_google_photos_media(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  ImageRef dco_decode_image_ref(dynamic raw);

  @protected
  IndexEvent dco_decode_index_event(dynamic raw);

  @protected
  IndexProgress dco_decode_index_progress(dynamic raw);

  @protected
  IndexStats dco_decode_index_stats(dynamic raw);

  @protected
  LinkCount dco_decode_link_count(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<AnchorRef> dco_decode_list_anchor_ref(dynamic raw);

  @protected
  List<BackLink> dco_decode_list_back_link(dynamic raw);

  @protected
  List<Block> dco_decode_list_block(dynamic raw);

  @protected
  List<ConflictFile> dco_decode_list_conflict_file(dynamic raw);

  @protected
  List<ImageRef> dco_decode_list_image_ref(dynamic raw);

  @protected
  List<LinkCount> dco_decode_list_link_count(dynamic raw);

  @protected
  List<MergeRegion> dco_decode_list_merge_region(dynamic raw);

  @protected
  List<NoteMeta> dco_decode_list_note_meta(dynamic raw);

  @protected
  List<NoteSpan> dco_decode_list_note_span(dynamic raw);

  @protected
  List<NoteTableCell> dco_decode_list_note_table_cell(dynamic raw);

  @protected
  List<NoteTableRow> dco_decode_list_note_table_row(dynamic raw);

  @protected
  List<ParseIssue> dco_decode_list_parse_issue(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<Resolution> dco_decode_list_resolution(dynamic raw);

  @protected
  List<TaskItem> dco_decode_list_task_item(dynamic raw);

  @protected
  List<TextMatch> dco_decode_list_text_match(dynamic raw);

  @protected
  List<TextSearchHit> dco_decode_list_text_search_hit(dynamic raw);

  @protected
  List<TwoHop> dco_decode_list_two_hop(dynamic raw);

  @protected
  MergeOutcome dco_decode_merge_outcome(dynamic raw);

  @protected
  MergeRegion dco_decode_merge_region(dynamic raw);

  @protected
  MergedNote dco_decode_merged_note(dynamic raw);

  @protected
  NoteMeta dco_decode_note_meta(dynamic raw);

  @protected
  NoteSpan dco_decode_note_span(dynamic raw);

  @protected
  NoteTableCell dco_decode_note_table_cell(dynamic raw);

  @protected
  NoteTableRow dco_decode_note_table_row(dynamic raw);

  @protected
  OpenGraphMeta dco_decode_open_graph_meta(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GitErrorKind? dco_decode_opt_box_autoadd_git_error_kind(dynamic raw);

  @protected
  GooglePhotosMedia? dco_decode_opt_box_autoadd_google_photos_media(
    dynamic raw,
  );

  @protected
  PendingConflict? dco_decode_opt_box_autoadd_pending_conflict(dynamic raw);

  @protected
  Suggestion? dco_decode_opt_box_autoadd_suggestion(dynamic raw);

  @protected
  TaskDate? dco_decode_opt_box_autoadd_task_date(dynamic raw);

  @protected
  TaskInfo? dco_decode_opt_box_autoadd_task_info(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_32(dynamic raw);

  @protected
  ParseIssue dco_decode_parse_issue(dynamic raw);

  @protected
  PattoError dco_decode_patto_error(dynamic raw);

  @protected
  PendingConflict dco_decode_pending_conflict(dynamic raw);

  @protected
  PendingGroup dco_decode_pending_group(dynamic raw);

  @protected
  RemoteCommit dco_decode_remote_commit(dynamic raw);

  @protected
  RenderedNote dco_decode_rendered_note(dynamic raw);

  @protected
  Resolution dco_decode_resolution(dynamic raw);

  @protected
  Suggestion dco_decode_suggestion(dynamic raw);

  @protected
  SuggestionKind dco_decode_suggestion_kind(dynamic raw);

  @protected
  SyncEvent dco_decode_sync_event(dynamic raw);

  @protected
  SyncReport dco_decode_sync_report(dynamic raw);

  @protected
  TaskDate dco_decode_task_date(dynamic raw);

  @protected
  TaskEditResult dco_decode_task_edit_result(dynamic raw);

  @protected
  TaskInfo dco_decode_task_info(dynamic raw);

  @protected
  TaskItem dco_decode_task_item(dynamic raw);

  @protected
  TaskStatus dco_decode_task_status(dynamic raw);

  @protected
  TextMatch dco_decode_text_match(dynamic raw);

  @protected
  TextSearchHit dco_decode_text_search_hit(dynamic raw);

  @protected
  TwoHop dco_decode_two_hop(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<CloneEvent> sse_decode_StreamSink_clone_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<IndexEvent> sse_decode_StreamSink_index_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SyncEvent> sse_decode_StreamSink_sync_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AnchorRef sse_decode_anchor_ref(SseDeserializer deserializer);

  @protected
  BackLink sse_decode_back_link(SseDeserializer deserializer);

  @protected
  Block sse_decode_block(SseDeserializer deserializer);

  @protected
  BlockKind sse_decode_block_kind(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  EmbedRef sse_decode_box_autoadd_embed_ref(SseDeserializer deserializer);

  @protected
  Failure sse_decode_box_autoadd_failure(SseDeserializer deserializer);

  @protected
  GitCreds sse_decode_box_autoadd_git_creds(SseDeserializer deserializer);

  @protected
  GitErrorKind sse_decode_box_autoadd_git_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  GitProgress sse_decode_box_autoadd_git_progress(SseDeserializer deserializer);

  @protected
  GooglePhotosMedia sse_decode_box_autoadd_google_photos_media(
    SseDeserializer deserializer,
  );

  @protected
  ImageRef sse_decode_box_autoadd_image_ref(SseDeserializer deserializer);

  @protected
  IndexProgress sse_decode_box_autoadd_index_progress(
    SseDeserializer deserializer,
  );

  @protected
  IndexStats sse_decode_box_autoadd_index_stats(SseDeserializer deserializer);

  @protected
  PendingConflict sse_decode_box_autoadd_pending_conflict(
    SseDeserializer deserializer,
  );

  @protected
  Suggestion sse_decode_box_autoadd_suggestion(SseDeserializer deserializer);

  @protected
  SyncReport sse_decode_box_autoadd_sync_report(SseDeserializer deserializer);

  @protected
  TaskDate sse_decode_box_autoadd_task_date(SseDeserializer deserializer);

  @protected
  TaskInfo sse_decode_box_autoadd_task_info(SseDeserializer deserializer);

  @protected
  int sse_decode_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  CloneEvent sse_decode_clone_event(SseDeserializer deserializer);

  @protected
  ConflictDetail sse_decode_conflict_detail(SseDeserializer deserializer);

  @protected
  ConflictFile sse_decode_conflict_file(SseDeserializer deserializer);

  @protected
  ConflictKind sse_decode_conflict_kind(SseDeserializer deserializer);

  @protected
  DateKind sse_decode_date_kind(SseDeserializer deserializer);

  @protected
  EmbedKind sse_decode_embed_kind(SseDeserializer deserializer);

  @protected
  EmbedRef sse_decode_embed_ref(SseDeserializer deserializer);

  @protected
  Failure sse_decode_failure(SseDeserializer deserializer);

  @protected
  GitCreds sse_decode_git_creds(SseDeserializer deserializer);

  @protected
  GitErrorKind sse_decode_git_error_kind(SseDeserializer deserializer);

  @protected
  GitPhase sse_decode_git_phase(SseDeserializer deserializer);

  @protected
  GitProgress sse_decode_git_progress(SseDeserializer deserializer);

  @protected
  GitStatus sse_decode_git_status(SseDeserializer deserializer);

  @protected
  GooglePhotosMedia sse_decode_google_photos_media(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  ImageRef sse_decode_image_ref(SseDeserializer deserializer);

  @protected
  IndexEvent sse_decode_index_event(SseDeserializer deserializer);

  @protected
  IndexProgress sse_decode_index_progress(SseDeserializer deserializer);

  @protected
  IndexStats sse_decode_index_stats(SseDeserializer deserializer);

  @protected
  LinkCount sse_decode_link_count(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<AnchorRef> sse_decode_list_anchor_ref(SseDeserializer deserializer);

  @protected
  List<BackLink> sse_decode_list_back_link(SseDeserializer deserializer);

  @protected
  List<Block> sse_decode_list_block(SseDeserializer deserializer);

  @protected
  List<ConflictFile> sse_decode_list_conflict_file(
    SseDeserializer deserializer,
  );

  @protected
  List<ImageRef> sse_decode_list_image_ref(SseDeserializer deserializer);

  @protected
  List<LinkCount> sse_decode_list_link_count(SseDeserializer deserializer);

  @protected
  List<MergeRegion> sse_decode_list_merge_region(SseDeserializer deserializer);

  @protected
  List<NoteMeta> sse_decode_list_note_meta(SseDeserializer deserializer);

  @protected
  List<NoteSpan> sse_decode_list_note_span(SseDeserializer deserializer);

  @protected
  List<NoteTableCell> sse_decode_list_note_table_cell(
    SseDeserializer deserializer,
  );

  @protected
  List<NoteTableRow> sse_decode_list_note_table_row(
    SseDeserializer deserializer,
  );

  @protected
  List<ParseIssue> sse_decode_list_parse_issue(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<Resolution> sse_decode_list_resolution(SseDeserializer deserializer);

  @protected
  List<TaskItem> sse_decode_list_task_item(SseDeserializer deserializer);

  @protected
  List<TextMatch> sse_decode_list_text_match(SseDeserializer deserializer);

  @protected
  List<TextSearchHit> sse_decode_list_text_search_hit(
    SseDeserializer deserializer,
  );

  @protected
  List<TwoHop> sse_decode_list_two_hop(SseDeserializer deserializer);

  @protected
  MergeOutcome sse_decode_merge_outcome(SseDeserializer deserializer);

  @protected
  MergeRegion sse_decode_merge_region(SseDeserializer deserializer);

  @protected
  MergedNote sse_decode_merged_note(SseDeserializer deserializer);

  @protected
  NoteMeta sse_decode_note_meta(SseDeserializer deserializer);

  @protected
  NoteSpan sse_decode_note_span(SseDeserializer deserializer);

  @protected
  NoteTableCell sse_decode_note_table_cell(SseDeserializer deserializer);

  @protected
  NoteTableRow sse_decode_note_table_row(SseDeserializer deserializer);

  @protected
  OpenGraphMeta sse_decode_open_graph_meta(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GitErrorKind? sse_decode_opt_box_autoadd_git_error_kind(
    SseDeserializer deserializer,
  );

  @protected
  GooglePhotosMedia? sse_decode_opt_box_autoadd_google_photos_media(
    SseDeserializer deserializer,
  );

  @protected
  PendingConflict? sse_decode_opt_box_autoadd_pending_conflict(
    SseDeserializer deserializer,
  );

  @protected
  Suggestion? sse_decode_opt_box_autoadd_suggestion(
    SseDeserializer deserializer,
  );

  @protected
  TaskDate? sse_decode_opt_box_autoadd_task_date(SseDeserializer deserializer);

  @protected
  TaskInfo? sse_decode_opt_box_autoadd_task_info(SseDeserializer deserializer);

  @protected
  int? sse_decode_opt_box_autoadd_u_32(SseDeserializer deserializer);

  @protected
  ParseIssue sse_decode_parse_issue(SseDeserializer deserializer);

  @protected
  PattoError sse_decode_patto_error(SseDeserializer deserializer);

  @protected
  PendingConflict sse_decode_pending_conflict(SseDeserializer deserializer);

  @protected
  PendingGroup sse_decode_pending_group(SseDeserializer deserializer);

  @protected
  RemoteCommit sse_decode_remote_commit(SseDeserializer deserializer);

  @protected
  RenderedNote sse_decode_rendered_note(SseDeserializer deserializer);

  @protected
  Resolution sse_decode_resolution(SseDeserializer deserializer);

  @protected
  Suggestion sse_decode_suggestion(SseDeserializer deserializer);

  @protected
  SuggestionKind sse_decode_suggestion_kind(SseDeserializer deserializer);

  @protected
  SyncEvent sse_decode_sync_event(SseDeserializer deserializer);

  @protected
  SyncReport sse_decode_sync_report(SseDeserializer deserializer);

  @protected
  TaskDate sse_decode_task_date(SseDeserializer deserializer);

  @protected
  TaskEditResult sse_decode_task_edit_result(SseDeserializer deserializer);

  @protected
  TaskInfo sse_decode_task_info(SseDeserializer deserializer);

  @protected
  TaskItem sse_decode_task_item(SseDeserializer deserializer);

  @protected
  TaskStatus sse_decode_task_status(SseDeserializer deserializer);

  @protected
  TextMatch sse_decode_text_match(SseDeserializer deserializer);

  @protected
  TextSearchHit sse_decode_text_search_hit(SseDeserializer deserializer);

  @protected
  TwoHop sse_decode_two_hop(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_clone_event_Sse(
    RustStreamSink<CloneEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_index_event_Sse(
    RustStreamSink<IndexEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sync_event_Sse(
    RustStreamSink<SyncEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_anchor_ref(AnchorRef self, SseSerializer serializer);

  @protected
  void sse_encode_back_link(BackLink self, SseSerializer serializer);

  @protected
  void sse_encode_block(Block self, SseSerializer serializer);

  @protected
  void sse_encode_block_kind(BlockKind self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_embed_ref(
    EmbedRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_failure(Failure self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_git_creds(
    GitCreds self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_error_kind(
    GitErrorKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_git_progress(
    GitProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_google_photos_media(
    GooglePhotosMedia self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_image_ref(
    ImageRef self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_index_progress(
    IndexProgress self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_index_stats(
    IndexStats self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_pending_conflict(
    PendingConflict self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_suggestion(
    Suggestion self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_sync_report(
    SyncReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_date(
    TaskDate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_task_info(
    TaskInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_clone_event(CloneEvent self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_detail(
    ConflictDetail self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_conflict_file(ConflictFile self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_kind(ConflictKind self, SseSerializer serializer);

  @protected
  void sse_encode_date_kind(DateKind self, SseSerializer serializer);

  @protected
  void sse_encode_embed_kind(EmbedKind self, SseSerializer serializer);

  @protected
  void sse_encode_embed_ref(EmbedRef self, SseSerializer serializer);

  @protected
  void sse_encode_failure(Failure self, SseSerializer serializer);

  @protected
  void sse_encode_git_creds(GitCreds self, SseSerializer serializer);

  @protected
  void sse_encode_git_error_kind(GitErrorKind self, SseSerializer serializer);

  @protected
  void sse_encode_git_phase(GitPhase self, SseSerializer serializer);

  @protected
  void sse_encode_git_progress(GitProgress self, SseSerializer serializer);

  @protected
  void sse_encode_git_status(GitStatus self, SseSerializer serializer);

  @protected
  void sse_encode_google_photos_media(
    GooglePhotosMedia self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_image_ref(ImageRef self, SseSerializer serializer);

  @protected
  void sse_encode_index_event(IndexEvent self, SseSerializer serializer);

  @protected
  void sse_encode_index_progress(IndexProgress self, SseSerializer serializer);

  @protected
  void sse_encode_index_stats(IndexStats self, SseSerializer serializer);

  @protected
  void sse_encode_link_count(LinkCount self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_anchor_ref(
    List<AnchorRef> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_back_link(List<BackLink> self, SseSerializer serializer);

  @protected
  void sse_encode_list_block(List<Block> self, SseSerializer serializer);

  @protected
  void sse_encode_list_conflict_file(
    List<ConflictFile> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_image_ref(List<ImageRef> self, SseSerializer serializer);

  @protected
  void sse_encode_list_link_count(
    List<LinkCount> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_merge_region(
    List<MergeRegion> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_meta(List<NoteMeta> self, SseSerializer serializer);

  @protected
  void sse_encode_list_note_span(List<NoteSpan> self, SseSerializer serializer);

  @protected
  void sse_encode_list_note_table_cell(
    List<NoteTableCell> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_note_table_row(
    List<NoteTableRow> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_parse_issue(
    List<ParseIssue> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_resolution(
    List<Resolution> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_task_item(List<TaskItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_text_match(
    List<TextMatch> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_text_search_hit(
    List<TextSearchHit> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_two_hop(List<TwoHop> self, SseSerializer serializer);

  @protected
  void sse_encode_merge_outcome(MergeOutcome self, SseSerializer serializer);

  @protected
  void sse_encode_merge_region(MergeRegion self, SseSerializer serializer);

  @protected
  void sse_encode_merged_note(MergedNote self, SseSerializer serializer);

  @protected
  void sse_encode_note_meta(NoteMeta self, SseSerializer serializer);

  @protected
  void sse_encode_note_span(NoteSpan self, SseSerializer serializer);

  @protected
  void sse_encode_note_table_cell(NoteTableCell self, SseSerializer serializer);

  @protected
  void sse_encode_note_table_row(NoteTableRow self, SseSerializer serializer);

  @protected
  void sse_encode_open_graph_meta(OpenGraphMeta self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_git_error_kind(
    GitErrorKind? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_google_photos_media(
    GooglePhotosMedia? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_pending_conflict(
    PendingConflict? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_suggestion(
    Suggestion? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_task_date(
    TaskDate? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_task_info(
    TaskInfo? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_32(int? self, SseSerializer serializer);

  @protected
  void sse_encode_parse_issue(ParseIssue self, SseSerializer serializer);

  @protected
  void sse_encode_patto_error(PattoError self, SseSerializer serializer);

  @protected
  void sse_encode_pending_conflict(
    PendingConflict self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_pending_group(PendingGroup self, SseSerializer serializer);

  @protected
  void sse_encode_remote_commit(RemoteCommit self, SseSerializer serializer);

  @protected
  void sse_encode_rendered_note(RenderedNote self, SseSerializer serializer);

  @protected
  void sse_encode_resolution(Resolution self, SseSerializer serializer);

  @protected
  void sse_encode_suggestion(Suggestion self, SseSerializer serializer);

  @protected
  void sse_encode_suggestion_kind(
    SuggestionKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_sync_event(SyncEvent self, SseSerializer serializer);

  @protected
  void sse_encode_sync_report(SyncReport self, SseSerializer serializer);

  @protected
  void sse_encode_task_date(TaskDate self, SseSerializer serializer);

  @protected
  void sse_encode_task_edit_result(
    TaskEditResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_task_info(TaskInfo self, SseSerializer serializer);

  @protected
  void sse_encode_task_item(TaskItem self, SseSerializer serializer);

  @protected
  void sse_encode_task_status(TaskStatus self, SseSerializer serializer);

  @protected
  void sse_encode_text_match(TextMatch self, SseSerializer serializer);

  @protected
  void sse_encode_text_search_hit(TextSearchHit self, SseSerializer serializer);

  @protected
  void sse_encode_two_hop(TwoHop self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
