// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'api/error.dart';
import 'api/git.dart';
import 'api/index.dart';
import 'api/tasks.dart';
import 'api/types.dart';
import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<List<NoteMeta>> listNotes({required String root}) =>
    RustLib.instance.api.crateFrbApiListNotes(root: root);

Future<String> readNote({required String root, required String relPath}) =>
    RustLib.instance.api.crateFrbApiReadNote(root: root, relPath: relPath);

Future<void> writeNote({
  required String root,
  required String relPath,
  required String content,
}) => RustLib.instance.api.crateFrbApiWriteNote(
  root: root,
  relPath: relPath,
  content: content,
);

Future<NoteMeta> createNote({
  required String root,
  required String name,
  required String initialContent,
}) => RustLib.instance.api.crateFrbApiCreateNote(
  root: root,
  name: name,
  initialContent: initialContent,
);

Future<void> deleteNote({required String root, required String relPath}) =>
    RustLib.instance.api.crateFrbApiDeleteNote(root: root, relPath: relPath);

Future<List<NoteMeta>> searchNotes({
  required String root,
  required String query,
  required int limit,
}) => RustLib.instance.api.crateFrbApiSearchNotes(
  root: root,
  query: query,
  limit: limit,
);

String? resolveWikiLink({required String root, required String name}) =>
    RustLib.instance.api.crateFrbApiResolveWikiLink(root: root, name: name);

String noteNameToRelPath({required String name}) =>
    RustLib.instance.api.crateFrbApiNoteNameToRelPath(name: name);

String relPathToNoteName({required String relPath}) =>
    RustLib.instance.api.crateFrbApiRelPathToNoteName(relPath: relPath);

Future<RenderedNote> renderNote({required String content}) =>
    RustLib.instance.api.crateFrbApiRenderNote(content: content);

/// Scan the notes directory and build the link index, streaming progress.
Stream<IndexProgress> indexBuild({required String root}) =>
    RustLib.instance.api.crateFrbApiIndexBuild(root: root);

Future<void> indexUpdateFile({required String root, required String relPath}) =>
    RustLib.instance.api.crateFrbApiIndexUpdateFile(
      root: root,
      relPath: relPath,
    );

/// Re-parse only the notes that changed on disk; used after a git sync.
Future<IndexStats> indexRefresh({required String root}) =>
    RustLib.instance.api.crateFrbApiIndexRefresh(root: root);

Future<List<BackLink>> backlinks({
  required String root,
  required String relPath,
}) => RustLib.instance.api.crateFrbApiBacklinks(root: root, relPath: relPath);

Future<List<TwoHop>> twoHopLinks({
  required String root,
  required String relPath,
}) => RustLib.instance.api.crateFrbApiTwoHopLinks(root: root, relPath: relPath);

Future<List<LinkCount>> linkCounts({required String root}) =>
    RustLib.instance.api.crateFrbApiLinkCounts(root: root);

bool noteExists({required String root, required String name}) =>
    RustLib.instance.api.crateFrbApiNoteExists(root: root, name: name);

Future<List<TaskItem>> pendingTasks({required String root}) =>
    RustLib.instance.api.crateFrbApiPendingTasks(root: root);

/// `timeframe` is one of `today`, `yesterday`, `this_week`, `last_week`,
/// `this_month`, `custom`; `from` / `to` are `YYYY-MM-DD` and only read for
/// `custom`.
Future<List<TaskItem>> completedTasks({
  required String root,
  required String timeframe,
  String? from,
  String? to,
}) => RustLib.instance.api.crateFrbApiCompletedTasks(
  root: root,
  timeframe: timeframe,
  from: from,
  to: to,
);

Future<TaskEditResult> setTaskStatus({
  required String root,
  required String relPath,
  required int row,
  required TaskStatus status,
}) => RustLib.instance.api.crateFrbApiSetTaskStatus(
  root: root,
  relPath: relPath,
  row: row,
  status: status,
);

/// Must be called before any other git function; see [`git::git_init_runtime`].
Future<void> gitInitRuntime({required String caBundlePath}) =>
    RustLib.instance.api.crateFrbApiGitInitRuntime(caBundlePath: caBundlePath);

Stream<GitProgress> gitClone({
  required String url,
  required String root,
  String? branch,
  required GitCreds creds,
}) => RustLib.instance.api.crateFrbApiGitClone(
  url: url,
  root: root,
  branch: branch,
  creds: creds,
);

Future<GitStatus> gitStatus({required String root}) =>
    RustLib.instance.api.crateFrbApiGitStatus(root: root);

Stream<GitProgress> gitSync({
  required String root,
  required String authorName,
  required String authorEmail,
  required GitCreds creds,
}) => RustLib.instance.api.crateFrbApiGitSync(
  root: root,
  authorName: authorName,
  authorEmail: authorEmail,
  creds: creds,
);
