[@code math]
raw sentence 

[` inline 1 [!() code]`] test [* bold] [*/ こんにちは] {@task until=2024/09/05} #anchor
{@task status=doing until=2020}
{@task until=2020}

[@code rust]
	fn sample_function() {
		println!("Hello from Rust!");
	}

link to [#tasks] or [self#tasks] or [sample#tasks]

{@anchor name=tag}

something to do   {@task status=doing until=2020-12-31}     #tasks
	テスト      {@task status=doing}
	テストテスト  {@task priority=high}
	重要なタスク  {@task status=done}


